set(ROCM_BUILD_FLAGS_PROTOCOL_VERSION 1)
set(ROCM_BUILD_FLAGS_PROVIDER "TheRock")
set(ROCM_BUILD_FLAGS_NAMES
  ROCM_BUILD_FLAGS_CANARY_BOOL_FALSE
  ROCM_BUILD_FLAGS_CANARY_BOOL_TRUE
  ROCM_BUILD_FLAGS_CANARY_INTEGER_NEGATIVE
  KPACK_SPLIT_ARTIFACTS
  HIPDNN_ENABLE_SDPA
  HIPBLASLTPROVIDER_ENABLE_MX_GEMM
  HIPKERNELPROVIDER_ENABLE_ROCKE
  HIPDNN_ENABLE_KERNEL_INGESTOR
  MIOPEN_ENABLE_HIPDNN_WRAPPER
  HIPDNN_ENABLE_CUDNN_COMPATIBILITY
  STAMP_LIBRARY_GIT_VERSIONS
  INCLUDE_HRX
  HSA_WINDOWS_SHARED_RUNTIME
  LLVM_ENABLE_ASSERTIONS
  WINDOWS_DRIVER_BUILD
)
set(ROCM_BUILD_FLAG_ROCM_BUILD_FLAGS_CANARY_BOOL_FALSE_TYPE "BOOL")
set(ROCM_BUILD_FLAG_ROCM_BUILD_FLAGS_CANARY_BOOL_FALSE_VALUE "0")
set(ROCM_BUILD_FLAG_ROCM_BUILD_FLAGS_CANARY_BOOL_TRUE_TYPE "BOOL")
set(ROCM_BUILD_FLAG_ROCM_BUILD_FLAGS_CANARY_BOOL_TRUE_VALUE "1")
set(ROCM_BUILD_FLAG_ROCM_BUILD_FLAGS_CANARY_INTEGER_NEGATIVE_TYPE "INTEGER")
set(ROCM_BUILD_FLAG_ROCM_BUILD_FLAGS_CANARY_INTEGER_NEGATIVE_VALUE "-17")
set(ROCM_BUILD_FLAG_KPACK_SPLIT_ARTIFACTS_TYPE "BOOL")
set(ROCM_BUILD_FLAG_KPACK_SPLIT_ARTIFACTS_VALUE "1")
set(ROCM_BUILD_FLAG_HIPDNN_ENABLE_SDPA_TYPE "BOOL")
set(ROCM_BUILD_FLAG_HIPDNN_ENABLE_SDPA_VALUE "0")
set(ROCM_BUILD_FLAG_HIPBLASLTPROVIDER_ENABLE_MX_GEMM_TYPE "BOOL")
set(ROCM_BUILD_FLAG_HIPBLASLTPROVIDER_ENABLE_MX_GEMM_VALUE "0")
set(ROCM_BUILD_FLAG_HIPKERNELPROVIDER_ENABLE_ROCKE_TYPE "BOOL")
set(ROCM_BUILD_FLAG_HIPKERNELPROVIDER_ENABLE_ROCKE_VALUE "0")
set(ROCM_BUILD_FLAG_HIPDNN_ENABLE_KERNEL_INGESTOR_TYPE "BOOL")
set(ROCM_BUILD_FLAG_HIPDNN_ENABLE_KERNEL_INGESTOR_VALUE "0")
set(ROCM_BUILD_FLAG_MIOPEN_ENABLE_HIPDNN_WRAPPER_TYPE "BOOL")
set(ROCM_BUILD_FLAG_MIOPEN_ENABLE_HIPDNN_WRAPPER_VALUE "0")
set(ROCM_BUILD_FLAG_HIPDNN_ENABLE_CUDNN_COMPATIBILITY_TYPE "BOOL")
set(ROCM_BUILD_FLAG_HIPDNN_ENABLE_CUDNN_COMPATIBILITY_VALUE "0")
set(ROCM_BUILD_FLAG_STAMP_LIBRARY_GIT_VERSIONS_TYPE "BOOL")
set(ROCM_BUILD_FLAG_STAMP_LIBRARY_GIT_VERSIONS_VALUE "0")
set(ROCM_BUILD_FLAG_INCLUDE_HRX_TYPE "BOOL")
set(ROCM_BUILD_FLAG_INCLUDE_HRX_VALUE "0")
set(ROCM_BUILD_FLAG_HSA_WINDOWS_SHARED_RUNTIME_TYPE "BOOL")
set(ROCM_BUILD_FLAG_HSA_WINDOWS_SHARED_RUNTIME_VALUE "0")
set(ROCM_BUILD_FLAG_LLVM_ENABLE_ASSERTIONS_TYPE "BOOL")
set(ROCM_BUILD_FLAG_LLVM_ENABLE_ASSERTIONS_VALUE "0")
set(ROCM_BUILD_FLAG_WINDOWS_DRIVER_BUILD_TYPE "BOOL")
set(ROCM_BUILD_FLAG_WINDOWS_DRIVER_BUILD_VALUE "0")
set(ROCM_BUILD_FLAGS_STATE_COMPLETE 1)
