name: "Setup test environment"

inputs:
  VENV_DIR:
    type: string
    required: true
  OUTPUT_ARTIFACTS_DIR:
    type: string
    required: true
  ARTIFACT_RUN_ID:
    type: string
  AMDGPU_FAMILIES:
    type: string
  FETCH_ARTIFACT_ARGS:
    type: string

runs:
  using: "composite"
  steps:
    - name: "Setting up Python"
      id: setup_python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: 3.11

    - name: Create Python venv
      shell: bash
      env:
        VENV_DIR: ${{ inputs.VENV_DIR }}
      run: |
        python -m venv ${VENV_DIR}
        source ${VENV_DIR}/bin/activate
        pip install -r requirements-test.txt
        pip freeze

    - name: Install the AWS tool
      shell: bash
      run: ./dockerfiles/cpubuilder/install_awscli.sh

    - name: Download and Unpack Artifacts
      shell: bash
      env:
        VENV_DIR: ${{ inputs.VENV_DIR }}
        OUTPUT_ARTIFACTS_DIR: ${{ inputs.OUTPUT_ARTIFACTS_DIR }}
        ARTIFACT_RUN_ID: ${{ inputs.ARTIFACT_RUN_ID }}
        AMDGPU_FAMILIES: ${{ inputs.AMDGPU_FAMILIES }}
        FETCH_ARTIFACT_ARGS: ${{ inputs.FETCH_ARTIFACT_ARGS }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        source ${VENV_DIR}/bin/activate

        python ./build_tools/install_rocm_from_artifacts.py \
          --run-id=${ARTIFACT_RUN_ID} \
          --amdgpu-family=${AMDGPU_FAMILIES} \
          --output-dir=${OUTPUT_ARTIFACTS_DIR} \
          ${FETCH_ARTIFACT_ARGS}
