#!/usr/bin/env python3
# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""Generate or verify the artifact_subprojects.json manifest.

This script runs a minimal cmake configure to generate the artifact->subproject
mappings, then either updates the committed manifest or verifies it's fresh.

Usage:
    # Regenerate the manifest
    python build_tools/generate_subproject_manifest.py

    # Verify the manifest is up-to-date (for CI)
    python build_tools/generate_subproject_manifest.py --verify

    # Specify a different GPU family
    python build_tools/generate_subproject_manifest.py --amdgpu-family gfx942
"""

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(
        description="Generate or verify artifact_subprojects.json manifest"
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Verify the manifest is up-to-date instead of regenerating",
    )
    parser.add_argument(
        "--amdgpu-family",
        default="gfx1100",
        help="AMDGPU family to use for cmake configure (default: gfx1100)",
    )
    args = parser.parse_args()

    # Paths
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent
    manifest_path = repo_root / "artifact_subprojects.json"

    # Create temp build directory
    with tempfile.TemporaryDirectory(prefix="therock-manifest-") as tmp_dir:
        build_dir = Path(tmp_dir)

        print(f"Running cmake configure in {build_dir}...")
        result = subprocess.run(
            [
                "cmake",
                "-B",
                str(build_dir),
                "-S",
                str(repo_root),
                "-GNinja",
                f"-DTHEROCK_AMDGPU_FAMILIES={args.amdgpu_family}",
                "-DTHEROCK_BUNDLE_SYSDEPS=OFF",
                "-DTHEROCK_ENABLE_ALL=ON",
                "-DTHEROCK_ENABLE_LIBHIPCXX=OFF",
            ],
            capture_output=True,
            text=True,
        )

        if result.returncode != 0:
            print("CMake configure failed:", file=sys.stderr)
            print(result.stderr, file=sys.stderr)
            sys.exit(1)

        # Check if manifest was generated
        generated_manifest = build_dir / "artifact_subprojects.json"
        if not generated_manifest.exists():
            print(
                "Error: artifact_subprojects.json not generated by cmake",
                file=sys.stderr,
            )
            sys.exit(1)

        # Load generated manifest
        with generated_manifest.open() as f:
            new_manifest = json.load(f)

        if args.verify:
            # Compare with existing manifest
            if not manifest_path.exists():
                print(
                    f"Error: {manifest_path} does not exist. "
                    "Run without --verify to generate it.",
                    file=sys.stderr,
                )
                sys.exit(1)

            with manifest_path.open() as f:
                old_manifest = json.load(f)

            if new_manifest == old_manifest:
                print("Manifest is up-to-date.")
                sys.exit(0)
            else:
                print(
                    "Error: artifact_subprojects.json is stale. "
                    "Run 'python build_tools/generate_subproject_manifest.py' "
                    "to regenerate it.",
                    file=sys.stderr,
                )
                # Show diff
                old_keys = set(old_manifest.keys())
                new_keys = set(new_manifest.keys())
                added = new_keys - old_keys
                removed = old_keys - new_keys
                if added:
                    print(f"  Added artifacts: {', '.join(sorted(added))}")
                if removed:
                    print(f"  Removed artifacts: {', '.join(sorted(removed))}")
                for key in old_keys & new_keys:
                    if old_manifest[key] != new_manifest[key]:
                        print(f"  Changed: {key}")
                sys.exit(1)
        else:
            # Update manifest
            shutil.copy(generated_manifest, manifest_path)
            print(f"Updated {manifest_path}")


if __name__ == "__main__":
    main()
