#!/usr/bin/env python3
# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT
"""
Generate the install-time CTestTestfile.cmake for ROCgdb.

Reads test_categories.yaml from a ROCgdb source tree and writes a small
CMake test file that contains one add_test() per tier
(quick/standard/comprehensive/full). Each add_test() is a bash wrapper that
invokes ROCgdb's existing test_rocgdb.py with --tier <name>; the tier-to-
test-pattern mapping itself lives in the YAML and is consumed by
test_rocgdb.py at runtime.

The generated file is installed to tests/rocgdb/CTestTestfile.cmake (next to
the already-installed testsuite tree) so TheRock's generic test_runner.py
can drive `ctest -L <tier> --test-dir <ROCM_PATH>/tests/rocgdb`.

The wrapper relies on the TEST_RUNNER_SCRIPT_PATH environment variable
being set by test_runner.py (via COMPONENT_OVERRIDES["rocgdb"]) before it
invokes ctest. This keeps the install file relocatable - it does not bake
in any absolute paths to TheRock's source tree.
"""

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write(
        "ERROR: PyYAML is required to generate the rocgdb CTestTestfile. "
        "Install it via `pip install pyyaml` and re-run.\n"
    )
    sys.exit(1)


VALID_TIERS = ("quick", "standard", "comprehensive", "full")


def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--yaml",
        type=Path,
        required=True,
        help="Path to ROCgdb's gdb/testsuite/test_categories.yaml.",
    )
    p.add_argument(
        "--out",
        type=Path,
        required=True,
        help="Output path for the generated CTestTestfile.cmake.",
    )
    return p.parse_args()


def _quote_labels(labels):
    # CTest LABELS property uses ';' as separator. Strip any stray ';' from
    # the YAML-supplied labels (defensive - YAML shouldn't have them, but
    # CTest would silently split on them and produce wrong labels).
    cleaned = [str(label).replace(";", "_") for label in labels]
    return ";".join(cleaned)


def render(yaml_path: Path) -> str:
    with yaml_path.open("r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    categories = cfg.get("test_categories") or {}
    execution_settings = cfg.get("execution_settings") or {}
    default_timeout = int(execution_settings.get("default_timeout", 300))
    category_timeouts = execution_settings.get("category_timeouts") or {}

    lines = [
        "# Generated by debug-tools/rocgdb/gen_install_ctestfile.py from",
        "# ROCgdb's gdb/testsuite/test_categories.yaml.  Do not edit by hand.",
        "#",
        "# Each test invokes test_rocgdb.py via a small bash wrapper. The",
        "# wrapper relies on TEST_RUNNER_SCRIPT_PATH being set in the",
        "# environment by TheRock's test_runner.py (see COMPONENT_OVERRIDES",
        "# for the 'rocgdb' job) so the install file stays relocatable.",
        "",
    ]

    emitted_any = False
    for tier in VALID_TIERS:
        spec = categories.get(tier)
        if not spec:
            continue
        labels = spec.get("labels") or [tier]
        timeout = int(category_timeouts.get(tier, default_timeout))
        # ctest test names must be bare CMake identifiers (no spaces / quotes)
        # so 'ctest --print-labels' and our parse_test_categories.py-style
        # consumers can match them by regex.
        test_name = f"rocgdb_{tier}"

        # bash -c '...' so the child shell expands ${TEST_RUNNER_SCRIPT_PATH}
        # at test runtime. Double quotes around the variable preserve paths
        # that contain spaces. The exit code of test_rocgdb.py becomes ctest's
        # exit code for this test.
        wrapper = (
            f'python3 "$TEST_RUNNER_SCRIPT_PATH" --tier {tier}'
        )

        lines.append(
            f'add_test({test_name} bash -c {_cmake_quote(wrapper)})'
        )
        lines.append(
            f'set_tests_properties({test_name} PROPERTIES'
        )
        lines.append(
            f'    LABELS "{_quote_labels(labels)}"'
        )
        lines.append(
            f'    TIMEOUT {timeout})'
        )
        lines.append("")
        emitted_any = True

    if not emitted_any:
        sys.stderr.write(
            f"ERROR: no test_categories.<tier> entries found in {yaml_path}\n"
        )
        sys.exit(1)

    return "\n".join(lines).rstrip() + "\n"


def _cmake_quote(s: str) -> str:
    # CMake add_test() arguments are space-separated. To embed a single
    # multi-word argument (the bash -c payload), wrap it in double quotes
    # and backslash-escape any embedded double quotes / backslashes.
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def main():
    args = parse_args()
    if not args.yaml.is_file():
        sys.stderr.write(f"ERROR: YAML file not found: {args.yaml}\n")
        sys.exit(1)

    content = render(args.yaml)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content, encoding="utf-8")
    print(f"Wrote {args.out} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
