#!/bin/bash
# ROCgdb launcher with proper library paths
# All work-item features included

SYSDEPS_LIBS=$(find /home/sulakshm/working/Debugger/TheRock/build -path "*/dist/lib/rocm_sysdeps/lib" -type d 2>/dev/null | tr '\n' ':')
export LD_LIBRARY_PATH="${SYSDEPS_LIBS}:/home/sulakshm/working/Debugger/TheRock/build/debug-tools/amd-dbgapi/dist/lib:/home/sulakshm/working/Debugger/TheRock/build/dist/rocm/lib"
export HSA_ENABLE_DEBUG=1

ROCGDB=/home/sulakshm/working/Debugger/TheRock/build/debug-tools/rocgdb/build/rocgdb-build-py3.11/gdb/gdb

exec "$ROCGDB" "$@"
