# rocSOLVER
[components.dbg."math-libs/rocSOLVER/stage"]
[components.dev."math-libs/rocSOLVER/stage"]
[components.doc."math-libs/rocSOLVER/stage"]
[components.lib."math-libs/rocSOLVER/stage"]

# hipSOLVER
[components.dbg."math-libs/hipSOLVER/stage"]
[components.dev."math-libs/hipSOLVER/stage"]
[components.doc."math-libs/hipSOLVER/stage"]
[components.lib."math-libs/hipSOLVER/stage"]
