[options]
unmatched_exclude = [
  "lib/rocm_sysdeps/share/man/**",
  "lib/rocm_sysdeps/share/info/**",
]

[components.dev."third-party/sysdeps/linux/libffi/build/stage"]
[components.lib."third-party/sysdeps/linux/libffi/build/stage"]
