name: "Checkout sources for Linux"

inputs:
  SUBTREE:
    type: string

runs:
  using: "composite"
  steps:
    - name: "Checking out repository"
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: "ROCm/TheRock"

    - name: Generate a token for rocm-libraries
      if: ${{ github.event.repository.name == 'rocm-libraries' }}
      id: generate-token
      uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
      with:
        app-id: ${{ secrets.rocm_libraries_app_id }}
        private-key: ${{ secrets.rocm_libraries_app_private_key }}
        owner: ${{ github.repository_owner }}

    - name: "Checking out repository for rocm-libraries"
      if: ${{ github.event.repository.name == 'rocm-libraries' }}
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: ${{ github.repository }}
        ref: refs/pull/${{ github.event.pull_request.number }}/merge
        sparse-checkout: |
          .github
          ${{ inputs.subtree }}
        fetch-depth: 0  # Needed for subtree splitting
        token: ${{ steps.generate-token.outputs.token }}
        path: "rocm-libraries"
