#ifndef MIRAGE_SIM_ISA_GFX1201_INTERPRETER_H_
#define MIRAGE_SIM_ISA_GFX1201_INTERPRETER_H_

#include <span>
#include <string>
#include <string_view>
#include <vector>

#include "lib/sim/isa/common/decoded_instruction.h"
#include "lib/sim/isa/common/execution_memory.h"
#include "lib/sim/isa/common/wave_execution_state.h"
#include "lib/sim/isa/gfx1201/architecture_profile.h"

namespace mirage::sim::isa {

enum class Gfx1201CompiledOpcode : std::uint8_t {
  kUnknown,
  kSEndpgm,
  kSNop,
  kSAddU32,
  kSAddI32,
  kSSubU32,
  kSCmpEqI32,
  kSCmpLgI32,
  kSCmpGtI32,
  kSCmpEqU32,
  kSCmpLgU32,
  kSCmpGeI32,
  kSCmpLtI32,
  kSCmpLeI32,
  kSCmpGtU32,
  kSCmpGeU32,
  kSCmpLtU32,
  kSCmpLeU32,
  kSBranch,
  kSCbranchScc0,
  kSCbranchScc1,
  kSCbranchVccz,
  kSCbranchVccnz,
  kSCbranchExecz,
  kSCbranchExecnz,
  kSMovB32,
  kSMovkI32,
  kVMovB32,
  kVCmpEqI32,
  kVCmpNeI32,
  kVCmpLtI32,
  kVCmpLeI32,
  kVCmpGtI32,
  kVCmpGeI32,
  kVCmpEqU32,
  kVCmpNeU32,
  kVCmpLtU32,
  kVCmpLeU32,
  kVCmpGtU32,
  kVCmpGeU32,
  kVCmpxEqI32,
  kVCmpxNeI32,
  kVCmpxLtI32,
  kVCmpxLeI32,
  kVCmpxGtI32,
  kVCmpxGeI32,
  kVCmpxEqU32,
  kVCmpxNeU32,
  kVCmpxLtU32,
  kVCmpxLeU32,
  kVCmpxGtU32,
  kVCmpxGeU32,
  kVCmpEqI64,
  kVCmpNeI64,
  kVCmpLtI64,
  kVCmpLeI64,
  kVCmpGtI64,
  kVCmpGeI64,
  kVCmpEqU64,
  kVCmpNeU64,
  kVCmpLtU64,
  kVCmpLeU64,
  kVCmpGtU64,
  kVCmpGeU64,
  kVCmpxEqI64,
  kVCmpxNeI64,
  kVCmpxLtI64,
  kVCmpxLeI64,
  kVCmpxGtI64,
  kVCmpxGeI64,
  kVCmpxEqU64,
  kVCmpxNeU64,
  kVCmpxLtU64,
  kVCmpxLeU64,
  kVCmpxGtU64,
  kVCmpxGeU64,
  kVCmpClassF32,
  kVCmpEqF32,
  kVCmpGeF32,
  kVCmpGtF32,
  kVCmpLeF32,
  kVCmpLgF32,
  kVCmpLtF32,
  kVCmpNeqF32,
  kVCmpOF32,
  kVCmpUF32,
  kVCmpNgeF32,
  kVCmpNlgF32,
  kVCmpNgtF32,
  kVCmpNleF32,
  kVCmpNltF32,
  kVCmpxClassF32,
  kVCmpxEqF32,
  kVCmpxGeF32,
  kVCmpxGtF32,
  kVCmpxLeF32,
  kVCmpxLgF32,
  kVCmpxLtF32,
  kVCmpxNeqF32,
  kVCmpxOF32,
  kVCmpxUF32,
  kVCmpxNgeF32,
  kVCmpxNlgF32,
  kVCmpxNgtF32,
  kVCmpxNleF32,
  kVCmpxNltF32,
  kVCmpClassF64,
  kVCmpEqF64,
  kVCmpGeF64,
  kVCmpGtF64,
  kVCmpLeF64,
  kVCmpLgF64,
  kVCmpLtF64,
  kVCmpNeqF64,
  kVCmpOF64,
  kVCmpUF64,
  kVCmpNgeF64,
  kVCmpNlgF64,
  kVCmpNgtF64,
  kVCmpNleF64,
  kVCmpNltF64,
  kVCmpxClassF64,
  kVCmpxEqF64,
  kVCmpxGeF64,
  kVCmpxGtF64,
  kVCmpxLeF64,
  kVCmpxLgF64,
  kVCmpxLtF64,
  kVCmpxNeqF64,
  kVCmpxOF64,
  kVCmpxUF64,
  kVCmpxNgeF64,
  kVCmpxNlgF64,
  kVCmpxNgtF64,
  kVCmpxNleF64,
  kVCmpxNltF64,
  kVNotB32,
  kVBfrevB32,
  kVCvtF32Ubyte0,
  kVCvtF32Ubyte1,
  kVCvtF32Ubyte2,
  kVCvtF32Ubyte3,
  kVCvtF32I32,
  kVCvtF32U32,
  kVCvtF32F64,
  kVCvtF64F32,
  kVCvtF64I32,
  kVCvtF64U32,
  kVCvtU32F32,
  kVCvtU32F64,
  kVCvtI32F32,
  kVCvtI32F64,
  kVTruncF32,
  kVCeilF32,
  kVRndneF32,
  kVFloorF32,
  kVTruncF64,
  kVCeilF64,
  kVRndneF64,
  kVFloorF64,
  kVAddU32,
  kVSubU32,
  kVSubrevU32,
  kVMinI32,
  kVMaxI32,
  kVMinU32,
  kVMaxU32,
  kVCndmaskB32,
  kVLshrrevB32,
  kVAshrrevI32,
  kVLshlrevB32,
  kVAndB32,
  kVOrB32,
  kVXorB32,
};

struct Gfx1201CompiledInstruction {
  Gfx1201CompiledOpcode opcode = Gfx1201CompiledOpcode::kUnknown;
  DecodedInstruction decoded_instruction;
};

class Gfx1201Interpreter {
 public:
  bool Supports(std::string_view opcode) const;
  bool CompileProgram(std::span<const DecodedInstruction> program,
                      std::vector<Gfx1201CompiledInstruction>* compiled_program,
                      std::string* error_message = nullptr) const;
  bool ExecuteProgram(std::span<const DecodedInstruction> program,
                      WaveExecutionState* state,
                      std::string* error_message = nullptr) const;
  bool ExecuteProgram(std::span<const DecodedInstruction> program,
                      WaveExecutionState* state,
                      ExecutionMemory* memory,
                      std::string* error_message) const;
  bool ExecuteProgram(std::span<const Gfx1201CompiledInstruction> program,
                      WaveExecutionState* state,
                      std::string* error_message = nullptr) const;
  bool ExecuteProgram(std::span<const Gfx1201CompiledInstruction> program,
                      WaveExecutionState* state,
                      ExecutionMemory* memory,
                      std::string* error_message) const;

  std::span<const std::string_view> ExecutableSeedOpcodes() const;
  std::span<const Gfx1201FamilyFocus> CarryOverFamilyFocus() const;
  std::span<const Gfx1201FamilyFocus> Rdna4DeltaFamilyFocus() const;
  std::string_view BringupStatus() const;
};

}  // namespace mirage::sim::isa

#endif  // MIRAGE_SIM_ISA_GFX1201_INTERPRETER_H_
