# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""
Compute subproject test dependencies from the consumer graph.

The consumer graph (build/therock_consumer_graph.json) is generated at CMake
configure time by therock_emit_consumer_graph(). It is a dynamic build artifact,
never committed: CI change-detection jobs run an on-demand `cmake` configure into
build/ before invoking this tool. If the graph is missing, run a configure first.

Algorithm
---------
1. Load the consumer graph: { subproject: { consumers: [...] } } from
   build/therock_consumer_graph.json.
2. Derive each subproject's build stage from the committed artifact descriptors
   (artifact-*.toml plus the unsuffixed base/artifact.toml) + BUILD_TOPOLOGY.toml
   (no CMake configure required for the stage map itself).
3. For each changed subproject, add its same-stage direct consumers.
4. Apply include/exclude/fanout overrides read from BUILD_TOPOLOGY.toml (the
   per-artifact test_include / test_exclude / test_fanout_all keys and the
   per-subproject [artifacts.<name>.test_overrides.<subproject>] sub-tables).

"Same-stage" means the consumer is in the same BUILD_TOPOLOGY build stage as
the changed subproject. Cross-stage consumers are universal deps (ROCR-Runtime,
hip-clr, compiler); enumerating them here would pull in the whole test tree, so
they are cut. Where a specific cross-stage or test-only coupling must still be
tested, it is listed explicitly via a test_include override in BUILD_TOPOLOGY.toml
(see the overrides for hip-clr / ROCR-Runtime). Foundational deps that have no
derivable stage (or whose consumers span every stage) rely on the
test_fanout_all override on artifact "base".

Example
-------
$ python test_tools/determine_rocm_test_dependencies.py --changed-projects rocSPARSE
["hipsparse", "rocsparse", "rocsolver", "hipsolver"]
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(
    0, str(Path(__file__).resolve().parents[1] / "build_tools" / "github_actions")
)
from github_actions_api import gha_set_output

sys.path.insert(
    0, str(Path(__file__).resolve().parents[1] / "build_tools" / "_therock_utils")
)

_CONSUMER_GRAPH_NAME = "therock_consumer_graph.json"


def _load_consumer_graph(therock_dir: Path) -> dict:
    """Load the dynamic consumer graph JSON from build/.

    The graph is produced by an on-demand `cmake` configure
    (therock_emit_consumer_graph). It is never committed; if it is missing the
    caller must run a configure first.
    """
    built = therock_dir / "build" / _CONSUMER_GRAPH_NAME
    if not built.exists():
        raise FileNotFoundError(
            f"Consumer graph not found at {built}.\n"
            "It is a dynamic build artifact generated by cmake configure. Run a "
            "configure first, e.g. `cmake -B build -GNinja -DTHEROCK_ENABLE_ALL=ON "
            "...`, which writes build/therock_consumer_graph.json."
        )
    return json.loads(built.read_text())


def _stage_path_subproject(component_key: str) -> str | None:
    """Extract the subproject name from an artifact-*.toml component key.

    Component keys are stage-relative paths such as "math-libs/rocRAND/stage" or
    "dctools/rdc/stage/portable-rdc". The subproject is the path segment directly
    before the "stage" segment. Returns None if there is no "stage" segment.
    """
    parts = component_key.split("/")
    try:
        stage_idx = parts.index("stage")
    except ValueError:
        return None
    if stage_idx == 0:
        return None
    return parts[stage_idx - 1].lower()


def _iter_artifact_tomls(therock_dir: Path):
    """Yield (artifact_name, toml_path) for every artifact descriptor.

    Scans the suffixed `artifact-*.toml` descriptors AND the unsuffixed
    `base/artifact.toml` (artifact name "base"). The plain glob misses
    base/artifact.toml, which is why rocm-core/rocm-cmake/rocm-half/
    rocprofiler-register never resolved a stage before; including it here fixes
    that gap so those foundational deps map to the stage owning artifact "base".
    """
    for toml_path in therock_dir.rglob("artifact-*.toml"):
        if "/build/" in toml_path.as_posix():
            continue
        yield toml_path.stem.removeprefix("artifact-"), toml_path

    base_toml = therock_dir / "base" / "artifact.toml"
    if base_toml.exists():
        yield "base", base_toml


def _build_subproject_maps(
    therock_dir: Path,
) -> tuple[dict[str, str], dict[str, str]]:
    """Return (subproject -> build_stage, subproject -> artifact) maps.

    Both are derived from the committed artifact descriptors + BUILD_TOPOLOGY.toml
    with no CMake metadata and no configure step:
      * subproject -> artifact: the artifact-*.toml (and base/artifact.toml)
        `components."<path>/stage"` keys; the artifact name is the file stem minus
        the "artifact-" prefix (or "base" for base/artifact.toml).
      * artifact -> build_stage: BuildTopology.get_stage_for_artifact().

    Subprojects that appear in no descriptor (foundation libs, third-party host
    deps) have no derivable stage/artifact and are omitted; callers treat a
    missing stage as "do not apply the same-stage cut" and defer to overrides.
    """
    try:
        import tomllib
    except ModuleNotFoundError:  # Python <= 3.10
        import tomli as tomllib

    try:
        from build_topology import get_topology
    except ImportError:
        return {}, {}

    try:
        topology = get_topology(therock_dir / "BUILD_TOPOLOGY.toml")
    except FileNotFoundError:
        return {}, {}

    subproject_to_stage: dict[str, str] = {}
    subproject_to_artifact: dict[str, str] = {}
    for artifact_name, toml_path in _iter_artifact_tomls(therock_dir):
        stage = topology.get_stage_for_artifact(artifact_name)
        data = tomllib.loads(toml_path.read_text())
        for entries in data.get("components", {}).values():
            if not isinstance(entries, dict):
                continue
            for component_key in entries:
                subproject = _stage_path_subproject(component_key)
                if not subproject:
                    continue
                subproject_to_artifact.setdefault(subproject, artifact_name)
                if stage:
                    subproject_to_stage.setdefault(subproject, stage)
    return subproject_to_stage, subproject_to_artifact


def _resolve_overrides(
    changed: list[str],
    artifact_of: dict[str, str],
    topology,
) -> dict[str, dict]:
    """Resolve BUILD_TOPOLOGY overrides for each changed subproject.

    Returns { subproject -> {test_include, test_exclude, test_fanout_all} } with
    lowercased include/exclude lists. A changed subproject with no owning
    artifact (or no topology) gets empty overrides.
    """
    resolved: dict[str, dict] = {}
    for proj in changed:
        artifact_name = artifact_of.get(proj)
        if not artifact_name or topology is None:
            resolved[proj] = {
                "test_include": [],
                "test_exclude": [],
                "test_fanout_all": False,
            }
            continue
        resolved[proj] = topology.get_test_overrides_for_subproject(
            artifact_name, proj
        )
    return resolved


def _get_topology(therock_dir: Path):
    """Load BuildTopology or return None if unavailable."""
    try:
        from build_topology import get_topology
    except ImportError:
        return None
    try:
        return get_topology(therock_dir / "BUILD_TOPOLOGY.toml")
    except FileNotFoundError:
        return None


def _apply_overrides(
    result: set, changed: list[str], overrides: dict[str, dict]
) -> set:
    """Apply include/exclude overrides for all changed projects in one pass.

    Overrides are applied once, after all same-stage consumers have been
    gathered, so exclude semantics are order-independent: an exclude for one
    changed project is not silently undone by another changed project adding the
    same consumer earlier or later in iteration. All includes are unioned first,
    then all excludes are subtracted.
    """
    for proj in changed:
        entry = overrides.get(proj, {})
        result.update(entry.get("test_include", []))
    for proj in changed:
        entry = overrides.get(proj, {})
        result.difference_update(entry.get("test_exclude", []))
    return result


def get_subprojects_to_test(
    changed_subprojects: list[str], therock_dir: Path | None = None
) -> set[str]:
    """Return the set of subproject names (lowercase) to test."""
    if therock_dir is None:
        therock_dir = Path.cwd()
    else:
        therock_dir = Path(therock_dir)

    graph = _load_consumer_graph(therock_dir)
    stage_of, artifact_of = _build_subproject_maps(therock_dir)
    topology = _get_topology(therock_dir)

    changed_lower = [p.lower() for p in changed_subprojects]
    overrides = _resolve_overrides(changed_lower, artifact_of, topology)

    # Warn on unrecognized projects (false-green typo guard).
    known = set(graph.keys())
    unknown = [p for p in changed_lower if p not in known]
    if unknown:
        print(
            f"Warning: unrecognized project(s) {unknown}; "
            "no tests will be selected for them",
            file=sys.stderr,
        )

    result = set(changed_lower)
    for proj in changed_lower:
        entry = graph.get(proj, {})
        consumers = entry.get("consumers", [])

        # Foundational fan-out: a project whose owning artifact is flagged
        # test_fanout_all in BUILD_TOPOLOGY selects ALL its graph consumers,
        # bypassing the same-stage cut. This is the opt-in for stage-less
        # foundational deps (rocm-cmake, rocm-core, ...) whose consumers span
        # every stage and would otherwise be selected by nothing. It stays
        # explicit per artifact: blanket-fanning every stage-less project would
        # re-expand universal deps (hip-clr, therock-googletest) into the whole
        # test tree.
        if overrides.get(proj, {}).get("test_fanout_all"):
            result.update(consumers)
            continue

        proj_stage = stage_of.get(proj)

        # A stage-less project (proj_stage is None: foundational deps like
        # rocm-core/rocm-cmake with no artifact descriptor) selects no consumers
        # via the same-stage cut; its dependents are covered by an explicit
        # test_fanout_all flag or test_include entries in BUILD_TOPOLOGY instead.
        for consumer in consumers:
            # Same-stage consumers only. Cross-stage deps (ROCR-Runtime, hip-clr,
            # compiler) would pull in the whole test tree; specific cross-stage /
            # test-only couplings that must run are listed as test_include
            # overrides in BUILD_TOPOLOGY rather than enumerated here.
            if proj_stage and stage_of.get(consumer) == proj_stage:
                result.add(consumer)

    # Apply overrides once, after all same-stage consumers are gathered, so
    # exclude is order-independent across multiple changed projects.
    result = _apply_overrides(result, changed_lower, overrides)

    return result


def list_subprojects(therock_dir: Path | None = None, show_deps: bool = False):
    """List all subprojects known to the consumer graph."""
    if therock_dir is None:
        therock_dir = Path.cwd()

    graph = _load_consumer_graph(Path(therock_dir))

    if show_deps:
        return {
            name: (entry["consumers"] if entry.get("consumers") else "empty")
            for name, entry in sorted(graph.items())
        }
    return sorted(graph.keys())


def main():
    parser = argparse.ArgumentParser(
        description="Compute subproject test dependencies from the consumer graph"
    )
    parser.add_argument(
        "--therock-dir", type=str, default=".", help="TheRock directory"
    )
    parser.add_argument(
        "--changed-projects",
        type=str,
        nargs="*",
        metavar="PROJECT",
        help="Project(s) that changed. Accepts space- or comma-separated list. "
        "Supports 'rocblas' or 'projects/rocblas' format.",
    )
    parser.add_argument(
        "--list-subprojects", action="store_true", help="List all known subprojects"
    )
    parser.add_argument(
        "--show-deps",
        action="store_true",
        help="With --list-subprojects, show consumers (or 'empty' if none)",
    )
    parser.add_argument(
        "--format",
        choices=["json", "list"],
        default="json",
        help="Output format: json (default) or list (newline-separated)",
    )
    parser.add_argument(
        "--gha-output",
        action="store_true",
        help="Write projects_to_test to GITHUB_OUTPUT",
    )

    args = parser.parse_args()
    therock_dir = Path(args.therock_dir).resolve()

    if args.list_subprojects:
        result = list_subprojects(therock_dir, show_deps=args.show_deps)
        print(json.dumps(result, indent=2))
        return

    # Parse and normalize changed_projects
    changed = args.changed_projects
    if changed:
        flattened = []
        for item in changed:
            flattened.extend(p.strip() for p in item.split(",") if p.strip())
        changed = flattened

    if changed:
        changed = [p.removeprefix("projects/") for p in changed]

    # No projects specified → all tests
    if not changed:
        if args.gha_output:
            gha_set_output({"projects_to_test": "*"})
        else:
            print("*")
        return

    result = get_subprojects_to_test(changed, therock_dir)
    projects_to_test = ",".join(sorted(result))

    if args.gha_output:
        gha_set_output({"projects_to_test": projects_to_test})
    elif args.format == "json":
        print(json.dumps(sorted(result)))
    else:
        for item in sorted(result):
            print(item)


if __name__ == "__main__":
    main()
