# clr
[components.dbg."core/clr/stage"]
[components.dev."core/clr/stage"]
[components.doc."core/clr/stage"]
[components.lib."core/clr/stage"]
include = [
  "lib/.hipInfo",
  "share/hip/**",
]
[components.run."core/clr/stage"]
include = [
  "bin/**",
]
