# ROCR-Runtime
[components.lib."core/ROCR-Runtime/stage"]
[components.run."core/ROCR-Runtime/stage"]
[components.dbg."core/ROCR-Runtime/stage"]
[components.dev."core/ROCR-Runtime/stage"]
[components.doc."core/ROCR-Runtime/stage"]

# rocminfo
[components.run."core/rocminfo/stage"]
[components.dbg."core/rocminfo/stage"]
[components.doc."core/rocminfo/stage"]

# hsa-hotswap (only built when THEROCK_ENABLE_HOTSWAP)
[components.lib."core/hsa-hotswap/stage"]
optional = true
[components.run."core/hsa-hotswap/stage"]
optional = true
[components.dbg."core/hsa-hotswap/stage"]
optional = true
[components.dev."core/hsa-hotswap/stage"]
optional = true
[components.doc."core/hsa-hotswap/stage"]
optional = true

# hrx
[components.lib."core/hrx/stage"]
optional = true
[components.run."core/hrx/stage"]
optional = true
include = [
  "lib/hrx/bin/**",
]
[components.dbg."core/hrx/stage"]
optional = true
[components.dev."core/hrx/stage"]
optional = true
include = [
  "lib/hrx/include/**",
  "lib/hrx/lib/cmake/**",
]
[components.doc."core/hrx/stage"]
optional = true
[components.test."core/hrx/stage"]
optional = true
include = [
  "lib/hrx/share/hrx-cts/**",
]
