#include "lib/sim/isa/gfx1250/target_catalog.h"

#include <array>

namespace mirage::sim::isa::gfx1250 {
namespace {

constexpr std::array<TargetOpcodeInfo, 172> kTargetOpcodeInfos{{
    {"S_CALL_B64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/SOPInstructions.td", 2629, true, false, false, false, false, false, false},
    {"S_GETPC_B64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/SOPInstructions.td", 2227, true, false, false, false, false, false, false},
    {"S_RFE_B64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/SOPInstructions.td", 2230, true, false, false, false, false, false, false},
    {"S_SETPC_B64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/SOPInstructions.td", 2228, true, false, false, false, false, false, false},
    {"S_SWAPPC_B64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/SOPInstructions.td", 2229, true, false, false, false, false, false, false},
    {"TENSOR_LOAD_TO_LDS", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/MIMGInstructions.td", 2142, false, true, false, false, true, false, false},
    {"TENSOR_STORE_FROM_LDS", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/MIMGInstructions.td", 2143, false, true, false, false, true, false, false},
    {"V_ADD_MAX_I32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2124, false, true, true, false, false, false, false},
    {"V_ADD_MAX_U32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2125, false, true, true, false, false, false, false},
    {"V_ADD_MIN_I32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2126, false, true, true, false, false, false, false},
    {"V_ADD_MIN_U32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2127, false, true, true, false, false, false, false},
    {"V_ASHRREV_I64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2295, true, false, true, false, false, false, false},
    {"V_ASHR_PK_I8_I32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2332, false, true, true, false, false, false, false},
    {"V_ASHR_PK_U8_I32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2333, false, true, true, false, false, false, false},
    {"V_BITOP3_B16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 1610, false, true, true, false, false, false, false},
    {"V_BITOP3_B32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2115, false, true, true, false, false, false, false},
    {"V_COS_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 1191, false, true, false, false, false, false, false},
    {"V_CVT_F16_BF8", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 1184, false, true, false, false, false, true, false},
    {"V_CVT_F16_FP8", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 1183, false, true, false, false, false, true, false},
    {"V_CVT_F32_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 318, false, true, false, false, false, false, false},
    {"V_CVT_F32_FP8", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 738, true, false, false, false, false, true, false},
    {"V_CVT_PK_BF16_F32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2379, false, true, true, false, false, false, false},
    {"V_CVT_PK_BF8_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 1809, false, true, true, false, false, true, false},
    {"V_CVT_PK_F16_BF8", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 1182, false, true, false, false, false, true, false},
    {"V_CVT_PK_F16_F32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2381, false, true, true, false, false, false, false},
    {"V_CVT_PK_F16_FP8", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 1181, false, true, false, false, false, true, false},
    {"V_CVT_PK_FP8_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 1804, false, true, true, false, false, true, false},
    {"V_CVT_PK_FP8_F32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 815, true, false, true, false, false, true, false},
    {"V_CVT_SCALEF32_PK16_BF6_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2363, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_PK16_BF6_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2361, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_PK16_BF6_F32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2359, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_PK16_FP6_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2362, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_PK16_FP6_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2360, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_PK16_FP6_F32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2358, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_PK8_BF8_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2346, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_PK8_BF8_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2351, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_PK8_BF8_F32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2350, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_PK8_FP4_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2347, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_PK8_FP4_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2344, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_PK8_FP4_F32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2343, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_PK8_FP8_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2345, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_PK8_FP8_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2349, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_PK8_FP8_F32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2348, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_SR_PK16_BF6_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2369, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_SR_PK16_BF6_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2367, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_SR_PK16_BF6_F32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2365, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_SR_PK16_FP6_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2368, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_SR_PK16_FP6_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2366, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_SR_PK16_FP6_F32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2364, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_SR_PK8_BF8_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2378, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_SR_PK8_BF8_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2377, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_SR_PK8_BF8_F32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2372, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_SR_PK8_FP4_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2374, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_SR_PK8_FP4_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2373, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_SR_PK8_FP4_F32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2370, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_SR_PK8_FP8_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2376, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_SR_PK8_FP8_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2375, false, true, true, false, false, true, true},
    {"V_CVT_SCALEF32_SR_PK8_FP8_F32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2371, false, true, true, false, false, true, true},
    {"V_CVT_SCALE_PK16_BF16_BF6", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2356, false, true, true, false, false, true, true},
    {"V_CVT_SCALE_PK16_BF16_FP6", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2353, false, true, true, false, false, true, true},
    {"V_CVT_SCALE_PK16_F16_BF6", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2355, false, true, true, false, false, true, true},
    {"V_CVT_SCALE_PK16_F16_FP6", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2352, false, true, true, false, false, true, true},
    {"V_CVT_SCALE_PK16_F32_BF6", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2357, false, true, true, false, false, true, true},
    {"V_CVT_SCALE_PK16_F32_FP6", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2354, false, true, true, false, false, true, true},
    {"V_CVT_SCALE_PK8_BF16_BF8", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2341, false, true, true, false, false, true, true},
    {"V_CVT_SCALE_PK8_BF16_FP4", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2335, false, true, true, false, false, true, true},
    {"V_CVT_SCALE_PK8_BF16_FP8", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2338, false, true, true, false, false, true, true},
    {"V_CVT_SCALE_PK8_F16_BF8", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2340, false, true, true, false, false, true, true},
    {"V_CVT_SCALE_PK8_F16_FP4", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2334, false, true, true, false, false, true, true},
    {"V_CVT_SCALE_PK8_F16_FP8", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2337, false, true, true, false, false, true, true},
    {"V_CVT_SCALE_PK8_F32_BF8", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2342, false, true, true, false, false, true, true},
    {"V_CVT_SCALE_PK8_F32_FP4", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2336, false, true, true, false, false, true, true},
    {"V_CVT_SCALE_PK8_F32_FP8", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2339, false, true, true, false, false, true, true},
    {"V_CVT_SR_BF8_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2386, false, true, true, false, false, true, false},
    {"V_CVT_SR_FP8_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2385, false, true, true, false, false, true, false},
    {"V_CVT_SR_FP8_F32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 826, true, false, true, false, false, true, false},
    {"V_CVT_SR_FP8_F32_gfx12", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2307, false, true, true, false, false, true, false},
    {"V_CVT_SR_PK_BF16_F32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2380, false, true, true, false, false, false, false},
    {"V_CVT_SR_PK_F16_F32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2382, false, true, true, false, false, false, false},
    {"V_DIV_FIXUP_F64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2218, true, false, true, false, false, false, false},
    {"V_DIV_FMAS_F64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2220, true, false, true, false, false, false, false},
    {"V_DIV_SCALE_F64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2262, true, false, true, false, false, false, true},
    {"V_EXP_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 1189, false, true, false, false, false, false, false},
    {"V_FMA_F64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2198, true, false, true, false, false, false, false},
    {"V_LDEXP_F64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2285, true, false, true, false, false, false, false},
    {"V_LOG_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 1188, false, true, false, false, false, false, false},
    {"V_LSHL_ADD_U64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2331, false, true, true, false, false, false, false},
    {"V_LSHRREV_B64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2294, true, false, true, false, false, false, false},
    {"V_MAD_NC_I64_I32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2119, false, true, true, false, false, false, false},
    {"V_MAD_NC_U64_U32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2118, false, true, true, false, false, false, false},
    {"V_MAD_U32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2117, false, true, true, false, false, false, false},
    {"V_MAX_I64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2123, false, true, true, false, false, false, false},
    {"V_MAX_U64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2121, false, true, true, false, false, false, false},
    {"V_MIN_I64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2122, false, true, true, false, false, false, false},
    {"V_MIN_U64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2120, false, true, true, false, false, false, false},
    {"V_MUL_HI_I32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2288, true, false, true, false, false, false, false},
    {"V_MUL_HI_U32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2287, true, false, true, false, false, false, false},
    {"V_MUL_LO_U32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2286, true, false, true, false, false, false, false},
    {"V_PERMLANE16_SWAP_B32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 1175, false, true, false, false, false, false, false},
    {"V_PERM_PK16_B4_U4", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2328, false, true, true, false, false, false, false},
    {"V_PERM_PK16_B6_U4", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2329, false, true, true, false, false, false, false},
    {"V_PERM_PK16_B8_U4", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3Instructions.td", 2330, false, true, true, false, false, false, false},
    {"V_PK_ADD_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2501, false, true, true, true, false, false, false},
    {"V_PK_ADD_MAX_I16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2492, false, true, true, true, false, false, false},
    {"V_PK_ADD_MAX_U16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2493, false, true, true, true, false, false, false},
    {"V_PK_ADD_MIN_I16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2494, false, true, true, true, false, false, false},
    {"V_PK_ADD_MIN_U16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2495, false, true, true, true, false, false, false},
    {"V_PK_FMA_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2500, false, true, true, true, false, false, false},
    {"V_PK_MAX3_I16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2496, false, true, true, true, false, false, false},
    {"V_PK_MAX3_NUM_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2508, false, true, true, true, false, false, false},
    {"V_PK_MAX3_U16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2497, false, true, true, true, false, false, false},
    {"V_PK_MAXIMUM3_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2506, false, true, true, true, false, false, false},
    {"V_PK_MAX_NUM_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2504, false, true, true, true, false, false, false},
    {"V_PK_MIN3_I16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2498, false, true, true, true, false, false, false},
    {"V_PK_MIN3_NUM_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2507, false, true, true, true, false, false, false},
    {"V_PK_MIN3_U16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2499, false, true, true, true, false, false, false},
    {"V_PK_MINIMUM3_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2505, false, true, true, true, false, false, false},
    {"V_PK_MIN_NUM_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2503, false, true, true, true, false, false, false},
    {"V_PK_MUL_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2502, false, true, true, true, false, false, false},
    {"V_RCP_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 1185, false, true, false, false, false, false, false},
    {"V_RSQ_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 1187, false, true, false, false, false, false, false},
    {"V_SAT_PK4_I4_I8", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 1179, false, true, false, false, false, false, false},
    {"V_SAT_PK4_U4_U8", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 1180, false, true, false, false, false, false, false},
    {"V_SIN_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 1190, false, true, false, false, false, false, false},
    {"V_SQRT_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 1186, false, true, false, false, false, false, false},
    {"V_SWMMAC_BF16F32_16X16X64_BF16_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2407, false, true, true, true, true, false, false},
    {"V_SWMMAC_BF16_16X16X64_BF16_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2406, false, true, true, true, true, false, false},
    {"V_SWMMAC_F16_16X16X128_BF8_BF8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2415, false, true, true, true, true, true, false},
    {"V_SWMMAC_F16_16X16X128_BF8_FP8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2414, false, true, true, true, true, true, false},
    {"V_SWMMAC_F16_16X16X128_FP8_BF8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2413, false, true, true, true, true, true, false},
    {"V_SWMMAC_F16_16X16X128_FP8_FP8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2412, false, true, true, true, true, true, false},
    {"V_SWMMAC_F16_16X16X64_F16_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2405, false, true, true, true, true, false, false},
    {"V_SWMMAC_F32_16X16X128_BF8_BF8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2411, false, true, true, true, true, true, false},
    {"V_SWMMAC_F32_16X16X128_BF8_FP8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2410, false, true, true, true, true, true, false},
    {"V_SWMMAC_F32_16X16X128_FP8_BF8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2409, false, true, true, true, true, true, false},
    {"V_SWMMAC_F32_16X16X128_FP8_FP8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2408, false, true, true, true, true, true, false},
    {"V_SWMMAC_F32_16X16X64_BF16_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2404, false, true, true, true, true, false, false},
    {"V_SWMMAC_F32_16X16X64_F16_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2403, false, true, true, true, true, false, false},
    {"V_SWMMAC_I32_16X16X128_IU8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2416, false, true, true, true, true, false, false},
    {"V_TANH_BF16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 1176, false, true, false, false, false, false, false},
    {"V_TANH_F16", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP1Instructions.td", 1174, false, true, false, false, false, false, false},
    {"V_WMMA_BF16F32_16X16X32_BF16_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2374, false, true, true, true, true, false, false},
    {"V_WMMA_BF16_16X16X32_BF16_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2373, false, true, true, true, true, false, false},
    {"V_WMMA_F16_16X16X128_BF8_BF8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2391, false, true, true, true, true, true, false},
    {"V_WMMA_F16_16X16X128_BF8_FP8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2390, false, true, true, true, true, true, false},
    {"V_WMMA_F16_16X16X128_FP8_BF8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2389, false, true, true, true, true, true, false},
    {"V_WMMA_F16_16X16X128_FP8_FP8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2388, false, true, true, true, true, true, false},
    {"V_WMMA_F16_16X16X32_F16_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2372, false, true, true, true, true, false, false},
    {"V_WMMA_F16_16X16X64_BF8_BF8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2382, false, true, true, true, true, true, false},
    {"V_WMMA_F16_16X16X64_BF8_FP8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2381, false, true, true, true, true, true, false},
    {"V_WMMA_F16_16X16X64_FP8_BF8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2380, false, true, true, true, true, true, false},
    {"V_WMMA_F16_16X16X64_FP8_FP8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2379, false, true, true, true, true, true, false},
    {"V_WMMA_F32_16X16X128_BF8_BF8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2387, false, true, true, true, true, true, false},
    {"V_WMMA_F32_16X16X128_BF8_FP8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2386, false, true, true, true, true, true, false},
    {"V_WMMA_F32_16X16X128_F8F6F4", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2395, false, true, true, true, true, true, false},
    {"V_WMMA_F32_16X16X128_FP8_BF8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2385, false, true, true, true, true, true, false},
    {"V_WMMA_F32_16X16X128_FP8_FP8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2384, false, true, true, true, true, true, false},
    {"V_WMMA_F32_16X16X32_BF16_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2370, false, true, true, true, true, false, false},
    {"V_WMMA_F32_16X16X32_F16_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2371, false, true, true, true, true, false, false},
    {"V_WMMA_F32_16X16X4_F32_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2369, false, true, true, true, true, false, false},
    {"V_WMMA_F32_16X16X64_BF8_BF8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2378, false, true, true, true, true, true, false},
    {"V_WMMA_F32_16X16X64_BF8_FP8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2377, false, true, true, true, true, true, false},
    {"V_WMMA_F32_16X16X64_FP8_BF8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2376, false, true, true, true, true, true, false},
    {"V_WMMA_F32_16X16X64_FP8_FP8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2375, false, true, true, true, true, true, false},
    {"V_WMMA_F32_32X16X128_F4_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2392, false, true, true, true, true, true, false},
    {"V_WMMA_I32_16X16X64_IU8_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2383, false, true, true, true, true, false, false},
    {"V_WMMA_LD_SCALE16_PAIRED_B64", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2515, false, true, true, true, true, false, true},
    {"V_WMMA_LD_SCALE_PAIRED_B32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2514, false, true, true, true, true, false, true},
    {"V_WMMA_SCALE16_F32_16X16X128_F8F6F4", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2397, false, true, true, true, true, true, true},
    {"V_WMMA_SCALE16_F32_32X16X128_F4_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2400, false, true, true, true, true, true, true},
    {"V_WMMA_SCALE_F32_16X16X128_F8F6F4", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2396, false, true, true, true, true, true, true},
    {"V_WMMA_SCALE_F32_32X16X128_F4_w32", "compiler/amd-llvm/llvm/lib/Target/AMDGPU/VOP3PInstructions.td", 2399, false, true, true, true, true, true, true},
}};

constexpr std::array<std::string_view, 32> kSharedInstructionSample{{
    "BUFFER_ATOMIC_ADD_F32",
    "BUFFER_ATOMIC_PK_ADD_BF16",
    "BUFFER_ATOMIC_PK_ADD_F16",
    "BUFFER_LOAD_FORMAT_X",
    "BUFFER_LOAD_FORMAT_XY",
    "BUFFER_LOAD_FORMAT_XYZ",
    "BUFFER_LOAD_FORMAT_XYZW",
    "BUFFER_STORE_FORMAT_X",
    "BUFFER_STORE_FORMAT_XY",
    "BUFFER_STORE_FORMAT_XYZ",
    "BUFFER_STORE_FORMAT_XYZW",
    "DS_ADD_F32",
    "DS_ADD_RTN_F32",
    "DS_ADD_RTN_U32",
    "DS_ADD_RTN_U64",
    "DS_ADD_U32",
    "DS_ADD_U64",
    "DS_AND_B32",
    "DS_AND_B64",
    "DS_AND_RTN_B32",
    "DS_AND_RTN_B64",
    "DS_APPEND",
    "DS_BPERMUTE_B32",
    "DS_CONDXCHG32_RTN_B64",
    "DS_CONSUME",
    "DS_DEC_RTN_U32",
    "DS_DEC_RTN_U64",
    "DS_DEC_U32",
    "DS_DEC_U64",
    "DS_INC_RTN_U32",
    "DS_INC_RTN_U64",
    "DS_INC_U32",
}};

constexpr std::array<std::string_view, 32> kRdna4OnlyInstructionSample{{
    "BUFFER_ATOMIC_ADD_U32",
    "BUFFER_ATOMIC_ADD_U64",
    "BUFFER_ATOMIC_AND_B32",
    "BUFFER_ATOMIC_AND_B64",
    "BUFFER_ATOMIC_CMPSWAP_B32",
    "BUFFER_ATOMIC_CMPSWAP_B64",
    "BUFFER_ATOMIC_COND_SUB_U32",
    "BUFFER_ATOMIC_DEC_U32",
    "BUFFER_ATOMIC_DEC_U64",
    "BUFFER_ATOMIC_INC_U32",
    "BUFFER_ATOMIC_INC_U64",
    "BUFFER_ATOMIC_MAX_I32",
    "BUFFER_ATOMIC_MAX_I64",
    "BUFFER_ATOMIC_MAX_NUM_F32",
    "BUFFER_ATOMIC_MAX_U32",
    "BUFFER_ATOMIC_MAX_U64",
    "BUFFER_ATOMIC_MIN_I32",
    "BUFFER_ATOMIC_MIN_I64",
    "BUFFER_ATOMIC_MIN_NUM_F32",
    "BUFFER_ATOMIC_MIN_U32",
    "BUFFER_ATOMIC_MIN_U64",
    "BUFFER_ATOMIC_OR_B32",
    "BUFFER_ATOMIC_OR_B64",
    "BUFFER_ATOMIC_SUB_CLAMP_U32",
    "BUFFER_ATOMIC_SUB_U32",
    "BUFFER_ATOMIC_SUB_U64",
    "BUFFER_ATOMIC_SWAP_B32",
    "BUFFER_ATOMIC_SWAP_B64",
    "BUFFER_ATOMIC_XOR_B32",
    "BUFFER_ATOMIC_XOR_B64",
    "BUFFER_LOAD_B128",
    "BUFFER_LOAD_B32",
}};

}  // namespace

std::span<const TargetOpcodeInfo> GetTargetOpcodeInfos() {
  return kTargetOpcodeInfos;
}

const TargetOpcodeInfo* FindTargetOpcodeInfo(std::string_view instruction_name) {
  for (const TargetOpcodeInfo& info : kTargetOpcodeInfos) {
    if (info.instruction_name == instruction_name) {
      return &info;
    }
  }
  return nullptr;
}

std::span<const std::string_view> GetSharedInstructionSample() {
  return kSharedInstructionSample;
}

std::span<const std::string_view> GetRdna4OnlyInstructionSample() {
  return kRdna4OnlyInstructionSample;
}

}  // namespace mirage::sim::isa::gfx1250
