# comgr and hipcc are considered part of the LLVM artifact (they are separated
# in the build tree because they need to be built separately in order to
# install to different prefixes).
[components.lib."compiler/amd-comgr/stage"]
[components.run."compiler/amd-comgr/stage"]
[components.dbg."compiler/amd-comgr/stage"]
[components.dev."compiler/amd-comgr/stage"]
[components.doc."compiler/amd-comgr/stage"]

# hipcc
[components.lib."compiler/hipcc/stage"]
[components.run."compiler/hipcc/stage"]
[components.dbg."compiler/hipcc/stage"]
[components.dev."compiler/hipcc/stage"]
[components.doc."compiler/hipcc/stage"]
