# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""Registry of the projects TheRock can build with code coverage.

Coverage is opt-in per project: instrumenting a library slows it down
substantially and only pays off for projects whose test suites are good enough
to produce a meaningful signal. `COVERAGE_PROJECTS` below is the allowlist, and
everything the coverage build needs to know about a project lives there.

`--emit-cmake PATH` writes the coverage group lists and the
THEROCK_COVERAGE_OPTION_<PROJECT> map as a CMake include. CMakeLists.txt runs
this on every configure, so this script must not depend on anything outside the
Python standard library.
"""

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

# Values for CoverageProject.source_repo: the repo a project ships from. Drives
# the THEROCK_COVERAGE_ROCM_LIBRARIES_ALL / _ROCM_SYSTEMS_ALL group lists.
ROCM_LIBRARIES = "rocm-libraries"
ROCM_SYSTEMS = "rocm-systems"


@dataclass(frozen=True)
class CoverageProject:
    """Everything the coverage pipeline needs to know about one project.

    Attributes:
        cmake_target: TheRock subproject name. Upper cased to form the
            `<PROJECT>_ENABLE_COVERAGE` flag, which is TheRock's own knob and
            is not what the subproject sees; see coverage_option.
        coverage_option: CMake option the upstream project implements to turn
            its instrumentation on. These names are not standardised -- most
            projects use `BUILD_CODE_COVERAGE` or `CODE_COVERAGE`, a few use
            `<PROJECT>_ENABLE_COVERAGE`, RCCL uses `ENABLE_CODE_COVERAGE` --
            so therock_subproject.cmake translates TheRock's flag into this
            name when configuring the subproject. Being per-subproject is what
            keeps the generic names from instrumenting the whole build. The
            option must select LLVM source-based coverage: gcov writes `.gcda`
            files, not the `.profraw` files this pipeline merges.
        source_repo: The repo this project ships from (ROCM_LIBRARIES or
            ROCM_SYSTEMS); picks its THEROCK_COVERAGE_*_ALL group.
    """

    cmake_target: str
    coverage_option: str
    source_repo: str = ROCM_LIBRARIES


# Projects that can be built with coverage instrumentation.
COVERAGE_PROJECTS: dict[str, CoverageProject] = {
    #
    # rocm-libraries -- math-libs stage
    #
    "hiprand": CoverageProject(
        cmake_target="hipRAND",
        coverage_option="BUILD_CODE_COVERAGE",
    ),
    "hipdnn": CoverageProject(
        cmake_target="hipDNN",
        coverage_option="HIPDNN_ENABLE_COVERAGE",
    ),
}

_VALID_SOURCE_REPOS = frozenset({ROCM_LIBRARIES, ROCM_SYSTEMS})
for _key, _proj in COVERAGE_PROJECTS.items():
    assert (
        _proj.source_repo in _VALID_SOURCE_REPOS
    ), f"{_key}: source_repo must be one of {sorted(_VALID_SOURCE_REPOS)}"
    # An entry without one would be accepted and instrument nothing.
    assert _proj.coverage_option, f"{_key}: coverage_option must be set"


def emit_cmake(output_path: Path) -> None:
    """Writes the coverage group lists and option-name map as a CMake include.

    The group lists drive the THEROCK_COVERAGE_*_ALL options. The option map
    tells therock_subproject.cmake which flag each subproject actually
    implements, since the names are not standardised upstream. CMakeLists.txt
    reads both so it does not hardcode either.
    """

    def targets(repo: str) -> list[str]:
        return sorted(
            (
                p.cmake_target
                for p in COVERAGE_PROJECTS.values()
                if p.source_repo == repo
            ),
            key=str.lower,
        )

    option_lines = [
        f"set(THEROCK_COVERAGE_OPTION_{p.cmake_target.upper()} {p.coverage_option})\n"
        for p in sorted(
            COVERAGE_PROJECTS.values(), key=lambda v: v.cmake_target.lower()
        )
    ]

    output_path.write_text(
        "# Generated by configure_coverage_ci.py --emit-cmake; do not edit.\n"
        "# Edit COVERAGE_PROJECTS in\n"
        "# build_tools/github_actions/configure_coverage_ci.py instead.\n"
        f"set(THEROCK_COVERAGE_ROCM_LIBRARIES_PROJECTS {' '.join(targets(ROCM_LIBRARIES))})\n"
        f"set(THEROCK_COVERAGE_ROCM_SYSTEMS_PROJECTS {' '.join(targets(ROCM_SYSTEMS))})\n"
        + "".join(option_lines)
    )


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--emit-cmake",
        type=Path,
        required=True,
        metavar="PATH",
        help="Write the coverage group lists as a CMake include to PATH, then exit.",
    )
    args = parser.parse_args(argv)
    emit_cmake(args.emit_cmake)
    return 0


if __name__ == "__main__":
    sys.exit(main())
