name: "Artifact upload"

inputs:
  BUILD_DIR:
    type: string
    required: true
  AMDGPU_FAMILIES:
    type: string
    required: true
  THEROCK_DIR:
    type: string
    description: "The path of TheRock directory (ex: `./TheRock`, `./`)"
    required: true
  AWS_ROLE:
    type: string
    default: arn:aws:iam::692859939525:role/therock-artifacts-external

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials for non-forked repos
      if: ${{ !github.event.pull_request.head.repo.fork }}
      uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
      with:
        aws-region: us-east-2
        role-to-assume: ${{ inputs.AWS_ROLE }}

    - name: Create Log archive
      shell: bash
      run: |
        python3 ${{ inputs.THEROCK_DIR }}/build_tools/create_log_archive.py \
          --build-dir=${{ inputs.BUILD_DIR }}

    - name: Create Logs index Files
      shell: bash
      run: |
        python3 ${{ inputs.THEROCK_DIR }}/build_tools/github_actions/create_log_index.py \
          --build-dir=${{ inputs.BUILD_DIR }} \
          --amdgpu-family=${{ inputs.AMDGPU_FAMILIES }}

    - name: Upload artifacts
      shell: bash
      run: |
        python ${{ inputs.THEROCK_DIR }}/build_tools/github_actions/upload_build_artifacts.py \
          --run-id ${{ github.run_id }} \
          --amdgpu-family ${{ inputs.AMDGPU_FAMILIES }} \
          --build-dir ${{ inputs.BUILD_DIR }}

    - name: Upload Logs
      shell: bash
      run: |
        python3 ${{ inputs.THEROCK_DIR }}/build_tools/github_actions/upload_build_logs_to_s3.py \
          --build-dir=${{ inputs.BUILD_DIR }} \
          --run-id ${{ github.run_id }} \
          --amdgpu-family ${{ inputs.AMDGPU_FAMILIES }}

    - name: Add Links to Job Summary
      shell: bash
      run: |
        python ${{ inputs.THEROCK_DIR }}/build_tools/github_actions/upload_build_summary.py \
          --run-id ${{ github.run_id }} \
          --amdgpu-family ${{ inputs.AMDGPU_FAMILIES }} \
          --build-dir ${{ inputs.BUILD_DIR }}
