import json
import logging
import os
import shlex
import subprocess
import tempfile
import tomllib
from pathlib import Path

THEROCK_BIN_DIR = os.getenv("THEROCK_BIN_DIR")
SCRIPT_DIR = Path(__file__).resolve().parent
THEROCK_DIR = SCRIPT_DIR.parent.parent.parent

logging.basicConfig(level=logging.INFO)

# Load test configuration from TOML (lists ALL plugins with paths/tolerances)
config_path = SCRIPT_DIR / "hipdnn_test_config.toml"
with open(config_path, "rb") as f:
    config = tomllib.load(f)
logging.info(f"Loaded test config from: {config_path}")

# Load build manifest produced by TheRock build - lists which plugins THIS build produced.
enabled_plugins_path = (
    Path(THEROCK_BIN_DIR)
    / "hipdnn_integration_tests_test_infra"
    / "build_enabled_hipdnn_plugins_manifest.json"
)
if not enabled_plugins_path.exists():
    raise RuntimeError(
        f"Missing {enabled_plugins_path}. "
        "This file is generated by CMake and should be present in the test artifact."
    )

with open(enabled_plugins_path) as f:
    enabled_plugins_data = json.load(f)
enabled_plugins = set(enabled_plugins_data.get("plugins", []))
logging.info(f"Build enabled plugins: {enabled_plugins}")

# Filter TOML config to only include plugins this build produced
if "plugins" in config:
    original_plugins = set(config["plugins"].keys())
    config["plugins"] = {
        name: cfg for name, cfg in config["plugins"].items() if name in enabled_plugins
    }
    filtered_plugins = set(config["plugins"].keys())
    if filtered_plugins != original_plugins:
        logging.info(f"Filtered plugins: {original_plugins} -> {filtered_plugins}")

# Filter engines to only include those from enabled plugins
if "engines" in config and "plugins" in config:
    # Collect all engine names from enabled plugins
    enabled_engines = set()
    for plugin_cfg in config["plugins"].values():
        enabled_engines.update(plugin_cfg.get("engines", []))

    # Filter engines section
    original_engines = set(config["engines"].keys())
    config["engines"] = {
        name: cfg for name, cfg in config["engines"].items() if name in enabled_engines
    }
    filtered_engines = set(config["engines"].keys())
    if filtered_engines != original_engines:
        logging.info(f"Filtered engines: {original_engines} -> {filtered_engines}")

# Flatten expected failures from all engines into a single set
all_expected_failures = set()
for engine_name, engine_cfg in config.get("engines", {}).items():
    for failure in engine_cfg.get("expected_failures", []):
        all_expected_failures.add(failure)
config["expected_failures"] = sorted(all_expected_failures)
if all_expected_failures:
    logging.info(
        f"Total expected failures across all engines: {len(all_expected_failures)}"
    )

# Write JSON config to temp file for C++ harness
fd, json_config_path = tempfile.mkstemp(suffix=".json", prefix="hipdnn_test_config_")
with os.fdopen(fd, "w") as f:
    json.dump(config, f)

os.environ["HIPDNN_TEST_CONFIG_PATH"] = json_config_path
logging.info(f"Wrote JSON config to: {json_config_path}")

cmd = [
    "ctest",
    "--test-dir",
    f"{THEROCK_BIN_DIR}/hipdnn_integration_tests_test_infra",
    "--output-on-failure",
    "--parallel",
    "8",
    "--timeout",
    "120",
]

logging.info(f"++ Exec [{THEROCK_DIR}]$ {shlex.join(cmd)}")

subprocess.run(
    cmd,
    cwd=THEROCK_DIR,
    check=True,
)
