# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

# Add repo root to PYTHONPATH
sys.path.insert(0, os.fspath(Path(__file__).parent.parent))
sys.path.insert(0, os.fspath(Path(__file__).parents[2]))

import configure_coverage_ci


class EmitCmakeTest(unittest.TestCase):
    def test_emits_group_lists_from_allowlist(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "therock_coverage_projects.cmake"
            self.assertEqual(configure_coverage_ci.main(["--emit-cmake", str(out)]), 0)
            text = out.read_text()
            libraries_line = next(
                line
                for line in text.splitlines()
                if line.startswith("set(THEROCK_COVERAGE_ROCM_LIBRARIES_PROJECTS")
            )
            self.assertIn("hipRAND", libraries_line)
            self.assertIn("hipDNN", libraries_line)
            # No rocm-systems project is onboarded yet; CMakeLists.txt warns
            # when THEROCK_COVERAGE_ROCM_SYSTEMS_ALL is set with an empty list.
            self.assertIn("set(THEROCK_COVERAGE_ROCM_SYSTEMS_PROJECTS )\n", text)

    def test_emits_the_upstream_option_name_per_subproject(self):
        # The generic names are why this is a per-subproject map: setting
        # BUILD_CODE_COVERAGE globally would instrument everything that happens
        # to understand it.
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "therock_coverage_projects.cmake"
            self.assertEqual(configure_coverage_ci.main(["--emit-cmake", str(out)]), 0)
            text = out.read_text()
            self.assertIn(
                "set(THEROCK_COVERAGE_OPTION_HIPRAND BUILD_CODE_COVERAGE)", text
            )
            self.assertIn(
                "set(THEROCK_COVERAGE_OPTION_HIPDNN HIPDNN_ENABLE_COVERAGE)", text
            )

    def test_emit_cmake_needs_no_env(self):
        # Must work without PROJECTS_TO_TEST / AMDGPU_FAMILIES / GITHUB_OUTPUT set.
        saved = {
            k: os.environ.pop(k, None)
            for k in (
                "PROJECTS_TO_TEST",
                "AMDGPU_FAMILIES",
                "COVERAGE_CONFIG_SOURCE",
                "GITHUB_OUTPUT",
            )
        }
        try:
            with tempfile.TemporaryDirectory() as tmp:
                out = Path(tmp) / "c.cmake"
                self.assertEqual(
                    configure_coverage_ci.main(["--emit-cmake", str(out)]), 0
                )
                self.assertTrue(out.exists())
        finally:
            for k, v in saved.items():
                if v is not None:
                    os.environ[k] = v

    def test_emit_cmake_runs_without_site_packages(self):
        # CMakeLists.txt runs this on every configure, with whatever Python it
        # found, so it must not import anything outside the standard library.
        script = Path(configure_coverage_ci.__file__)
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "c.cmake"
            subprocess.run(
                [sys.executable, "-I", "-S", os.fspath(script), "--emit-cmake", out],
                check=True,
            )
            self.assertTrue(out.read_text().startswith("# Generated by"))


if __name__ == "__main__":
    unittest.main()
