[options]
unmatched_exclude = [
  # The LLVM install also emits per config CMake objects directories. These
  # are ok to ignore.
  "lib/llvm/lib/objects-*/**",

  # Various docs or utilities we don't care about.
  "lib/llvm/share/clang-doc/**",
  "lib/llvm/share/clang/**",
]

# LLVM deviates from the defaults in some key ways:
#   lib/llvm/clang : Contains a prefix like tree that must always be
#     accessible for library use, regardless of file type/association
#     (and should be excluded from other components).
[components.lib."base/amd-llvm/stage"]
include = [
  "lib/llvm/amdgcn/**",
  "lib/llvm/lib/*.bc",
  "lib/llvm/lib/*.ll",
  "lib/llvm/lib/*.modules.json",
  "lib/llvm/include/c++/**",
]
force_include = [
  "lib/llvm/lib/clang/**",
]

[components.run."base/amd-llvm/stage"]
include = [
  "lib/llvm/bin/**",
  "lib/llvm/libexec/**",
  "lib/llvm/hip/**",
]
exclude = [
  "lib/llvm/lib/clang/**",
]

[components.dbg."base/amd-llvm/stage"]

[components.dev."base/amd-llvm/stage"]
include = [
  "lib/llvm/share/libc++/**",
]
exclude = [
  "lib/llvm/lib/clang/**",
]

[components.doc."base/amd-llvm/stage"]
