# hipBLAS-common
[components.dbg."math-libs/hipBLAS-common/stage"]
[components.dev."math-libs/hipBLAS-common/stage"]
[components.doc."math-libs/hipBLAS-common/stage"]
[components.lib."math-libs/hipBLAS-common/stage"]

# hipBLAS
[components.dbg."math-libs/hipBLAS/stage"]
[components.dev."math-libs/hipBLAS/stage"]
[components.doc."math-libs/hipBLAS/stage"]
[components.lib."math-libs/hipBLAS/stage"]

# hipBLASLt
[components.dbg."math-libs/hipBLASLt/stage"]
[components.dev."math-libs/hipBLASLt/stage"]
[components.doc."math-libs/hipBLASLt/stage"]
[components.lib."math-libs/hipBLASLt/stage"]
include = [
  "lib/hipblaslt/library/**",
]

# rocBLAS
[components.dbg."math-libs/rocBLAS/stage"]
[components.dev."math-libs/rocBLAS/stage"]
[components.doc."math-libs/rocBLAS/stage"]
[components.lib."math-libs/rocBLAS/stage"]

# rocSOLVER
[components.dbg."math-libs/rocSOLVER/stage"]
optional = true
[components.dev."math-libs/rocSOLVER/stage"]
optional = true
[components.doc."math-libs/rocSOLVER/stage"]
optional = true
[components.lib."math-libs/rocSOLVER/stage"]
optional = true

# hipSOLVER
[components.dbg."math-libs/hipSOLVER/stage"]
optional = true
[components.dev."math-libs/hipSOLVER/stage"]
optional = true
[components.doc."math-libs/hipSOLVER/stage"]
optional = true
[components.lib."math-libs/hipSOLVER/stage"]
optional = true

# rocSPARSE
[components.dbg."math-libs/rocSPARSE/stage"]
optional = true
[components.dev."math-libs/rocSPARSE/stage"]
optional = true
[components.doc."math-libs/rocSPARSE/stage"]
optional = true
[components.lib."math-libs/rocSPARSE/stage"]
optional = true

# hipSPARSE
[components.dbg."math-libs/hipSPARSE/stage"]
optional = true
[components.dev."math-libs/hipSPARSE/stage"]
optional = true
[components.doc."math-libs/hipSPARSE/stage"]
optional = true
[components.lib."math-libs/hipSPARSE/stage"]
optional = true
