# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

# rocSOLVER
[components.lib."math-libs/BLAS/rocSOLVER/stage"]
optional = true
[components.dbg."math-libs/BLAS/rocSOLVER/stage"]
optional = true
[components.dev."math-libs/BLAS/rocSOLVER/stage"]
optional = true
[components.doc."math-libs/BLAS/rocSOLVER/stage"]
optional = true
[components.test."math-libs/BLAS/rocSOLVER/stage"]
include = [
  "bin/rocsolver-bench*",
  # Clients tests (test_runner runs ctest from bin/rocsolver/; needs CTestTestfile.cmake)
  "bin/rocsolver/**",
  "bin/rocsolver-test*",
  "share/rocsolver/test/**",
]
optional = true

# hipSOLVER
[components.lib."math-libs/BLAS/hipSOLVER/stage"]
exclude = [
  "lib/libhipsolver_fortran.so*",
]
optional = true
[components.dbg."math-libs/BLAS/hipSOLVER/stage"]
optional = true
[components.dev."math-libs/BLAS/hipSOLVER/stage"]
optional = true
[components.doc."math-libs/BLAS/hipSOLVER/stage"]
optional = true
[components.test."math-libs/BLAS/hipSOLVER/stage"]
include = [
  "bin/hipsolver-bench*",
  # Clients tests (test_runner runs ctest from bin/hipsolver/; needs CTestTestfile.cmake)
  "bin/hipsolver/**",
  "bin/hipsolver-test*",
  "lib/libhipsolver_fortran.so*",
  "share/hipsolver/test/**",
]
optional = true
