# hipBLAS-common
[components.dbg."math-libs/BLAS/hipBLAS-common/stage"]
[components.dev."math-libs/BLAS/hipBLAS-common/stage"]
[components.doc."math-libs/BLAS/hipBLAS-common/stage"]
[components.lib."math-libs/BLAS/hipBLAS-common/stage"]

# hipBLAS
[components.dbg."math-libs/BLAS/hipBLAS/stage"]
[components.dev."math-libs/BLAS/hipBLAS/stage"]
[components.doc."math-libs/BLAS/hipBLAS/stage"]
[components.lib."math-libs/BLAS/hipBLAS/stage"]

# hipBLASLt
[components.dbg."math-libs/BLAS/hipBLASLt/stage"]
[components.dev."math-libs/BLAS/hipBLASLt/stage"]
[components.doc."math-libs/BLAS/hipBLASLt/stage"]
[components.lib."math-libs/BLAS/hipBLASLt/stage"]
include = [
  "lib/hipblaslt/library/**",
]
[components.test."math-libs/BLAS/hipBLASLt/stage"]
include = [
  # Clients benchmarks
  "bin/hipblaslt-bench",
  "bin/hipblaslt-bench-*",
  "bin/hipblaslt-sequence",
  "bin/sequence.yaml",
  # Clients tests
  "bin/hipblaslt-test",
  "bin/hipblaslt_gentest.py",
  "bin/hipblaslt_gtest.data",
  "bin/hipblaslt_*.yaml",
]

# rocBLAS
[components.dbg."math-libs/BLAS/rocBLAS/stage"]
[components.dev."math-libs/BLAS/rocBLAS/stage"]
[components.doc."math-libs/BLAS/rocBLAS/stage"]
[components.lib."math-libs/BLAS/rocBLAS/stage"]
include = [
  "lib/rocblas/library/**",
]
[components.test."math-libs/BLAS/rocBLAS/stage"]
include = [
  # Clients benchmarks
  "bin/rocblas-bench",
  "bin/rocblas-gemm-tune",
  # Clients tests
  "bin/rocblas-test",
  "bin/rocblas_gentest.py",
  "bin/rocblas_gtest.data",
  "bin/rocblas_*.yaml",
]

# rocSOLVER
[components.dbg."math-libs/BLAS/rocSOLVER/stage"]
optional = true
[components.dev."math-libs/BLAS/rocSOLVER/stage"]
optional = true
[components.doc."math-libs/BLAS/rocSOLVER/stage"]
optional = true
[components.lib."math-libs/BLAS/rocSOLVER/stage"]
optional = true

# hipSOLVER
[components.dbg."math-libs/BLAS/hipSOLVER/stage"]
optional = true
[components.dev."math-libs/BLAS/hipSOLVER/stage"]
optional = true
[components.doc."math-libs/BLAS/hipSOLVER/stage"]
optional = true
[components.lib."math-libs/BLAS/hipSOLVER/stage"]
optional = true

# rocSPARSE
[components.dbg."math-libs/BLAS/rocSPARSE/stage"]
optional = true
[components.dev."math-libs/BLAS/rocSPARSE/stage"]
optional = true
[components.doc."math-libs/BLAS/rocSPARSE/stage"]
optional = true
[components.lib."math-libs/BLAS/rocSPARSE/stage"]
optional = true

# hipSPARSE
[components.dbg."math-libs/BLAS/hipSPARSE/stage"]
optional = true
[components.dev."math-libs/BLAS/hipSPARSE/stage"]
optional = true
[components.doc."math-libs/BLAS/hipSPARSE/stage"]
optional = true
[components.lib."math-libs/BLAS/hipSPARSE/stage"]
optional = true
