# hipDNN Integration Tests
[components.test."ml-libs/hipdnn_integration_tests/stage"]
include = [
  "bin/hipdnn_integration_tests",
  "bin/*hipdnn_*_test*",
  "bin/integration_tests/CTestTestfile.cmake",
]
[components.run."ml-libs/hipdnn_integration_tests/stage"]
include = [
  "bin/hipdnn_integration_tests",
  "bin/*hipdnn_*_test*"
]
