# hipDNN
[components.dbg."ml-libs/hipDNN/stage"]
[components.dev."ml-libs/hipDNN/stage"]
[components.doc."ml-libs/hipDNN/stage"]
[components.lib."ml-libs/hipDNN/stage"]
exclude = [
  "lib/libhipdnn_backend_private.a",
  "lib/test_plugins/**",
]
[components.test."ml-libs/hipDNN/stage"]
include = [
  "bin/*hipdnn_*_tests*",
  "bin/hipdnn/CTestTestfile.cmake",
  "lib/test_plugins/**",
]
[components.run."ml-libs/hipDNN/stage"]
