# Add the plugin engines directory to the private install RPATH dirs for the unit tests that use the plugin.so
list(APPEND THEROCK_PRIVATE_INSTALL_RPATH_DIRS "lib/hipdnn_plugins/engines")

# Install the plugin manifest generated by ml-libs/CMakeLists.txt.
# The manifest is written there (top-level) where THEROCK_ENABLE_*_PLUGIN variables
# are available, and installed here during the subproject's stage phase.
set(_manifest_file "${THEROCK_BINARY_DIR}/ml-libs/build_enabled_hipdnn_plugins_manifest.json")
install(FILES "${_manifest_file}" DESTINATION "${CMAKE_INSTALL_BINDIR}/hipdnn_integration_tests_test_infra")
