# Generate a JSON file containing key metadata about the current build
# configuration for processing by other tools.

function(therock_introspect_subprojects)
  include(therock_subproject_utils)
  therock_get_all_targets(all_targets "${CMAKE_CURRENT_SOURCE_DIR}")
  set(info "{")
  set(first TRUE)
  foreach(target ${all_targets})
    get_target_property(_is_subproject ${target} THEROCK_SUBPROJECT)
    if (NOT _is_subproject STREQUAL "cmake")
      string(FIND ${target} "+" plusloc)
      if (NOT plusloc EQUAL -1)
        string(LENGTH ${target} strlen)
        string(SUBSTRING ${target} 0 ${plusloc} subproject_part)
        math(EXPR plusloc "${plusloc}+1")
        string(SUBSTRING ${target} ${plusloc} ${strlen} action_part)
        list(APPEND "actions_${subproject_part}" "\"${action_part}\"")
      endif()
    endif()
  endforeach()
  foreach(target ${all_targets})
    get_target_property(_is_subproject ${target} THEROCK_SUBPROJECT)
    if (_is_subproject STREQUAL "cmake")
      if(NOT ${first})
        set(info "${info},\n")
      endif()
      set(info "${info}\"${target}\":\n")
      get_target_property(src_dir ${target} THEROCK_CMAKE_SOURCE_DIR)
      get_target_property(bin_dir ${target} THEROCK_BINARY_DIR)
      get_target_property(install_dest ${target} THEROCK_INSTALL_DESTINATION)
      get_target_property(build_deps ${target} THEROCK_BUILD_DEPS)
      get_target_property(runtime_deps ${target} THEROCK_RUNTIME_DEPS)
      get_target_property(build_pool ${target} THEROCK_BUILD_POOL)
      get_target_property(compiler_toolchain ${target} THEROCK_COMPILER_TOOLCHAIN)
      file(RELATIVE_PATH rel_srcdir ${CMAKE_SOURCE_DIR} ${src_dir})
      file(RELATIVE_PATH rel_bindir ${CMAKE_BINARY_DIR} ${bin_dir})
      set(info "${info}{ \"src\": \"${rel_srcdir}\",\n")
      set(info "${info}  \"bin\": \"${rel_bindir}\",\n")
      set(info "${info}  \"install_dest\": \"${install_dest}\",\n")
      set(quoted_build_deps)
      foreach(dep ${build_deps})
        list(APPEND quoted_build_deps "\"${dep}\"")
      endforeach()
      list(JOIN quoted_build_deps "," deplist)
      set(info "${info}  \"build_deps\": [ ${deplist} ],\n")
      set(quoted_runtime_deps)
      foreach(dep ${runtime_deps})
        list(APPEND quoted_runtime_deps "\"${dep}\"")
      endforeach()
      list(JOIN quoted_runtime_deps "," rundeplist)
      set(info "${info}  \"runtime_deps\": [ ${rundeplist} ],\n")
      set(info "${info}  \"build_pool\": \"${build_pool}\",\n")
      set(info "${info}  \"compiler_toolchain\": \"${compiler_toolchain}\",\n")
      list(JOIN "actions_${target}" "," actionlist)
      set(info "${info}  \"actions\": [ ${actionlist} ] }")
      set(first FALSE)
    endif()
  endforeach()
  set(info "${info}\n}")

  file(WRITE ${CMAKE_BINARY_DIR}/subproject_map.json "${info}")
endfunction()
