#!/usr/bin/env python3

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path


SCRIPT_PATH = Path(__file__).resolve()
MIRAGE_ROOT = SCRIPT_PATH.parents[3]

INVENTORY_PATH = (
    MIRAGE_ROOT / "tests" / "data" / "architecture_import" / "gfx1201" /
    "gfx1201_instruction_inventory.json"
)
SUPPORT_MATRIX_PATH = (
    MIRAGE_ROOT / "reports" / "architectures" / "gfx1201" /
    "gfx1201_support_matrix.json"
)

DECODER_SEED_CC_PATH = (
    MIRAGE_ROOT / "native" / "src" / "isa" / "gfx1201" / "decoder_seed.cc"
)
REPORT_DIR = MIRAGE_ROOT / "reports" / "architectures" / "gfx1201"
REPORT_JSON_PATH = REPORT_DIR / "gfx1201_phase0_compute_decoder_seed.json"
REPORT_MD_PATH = REPORT_DIR / "gfx1201_phase0_compute_decoder_seed.md"

STATE_ORDER = [
    "transferable_as_is",
    "transferable_with_decoder_work",
    "transferable_with_semantic_work",
    "transferable_with_decoder_and_semantic_work",
    "gfx1201_specific",
]

PHASE0_ENCODINGS = [
    (
        "ENC_SOPP",
        "S_ENDPGM",
        "Program control, wait/event sequencing, and branch bring-up.",
    ),
    (
        "ENC_SOP1",
        "S_MOV_B32",
        "Scalar move, bit-manipulation, and exec-mask setup precedent.",
    ),
    (
        "ENC_SOP2",
        "S_AND_B32",
        "Scalar binary core needed before wider control-flow work.",
    ),
    (
        "ENC_SOPC",
        "S_CMP_EQ_U32",
        "Scalar compare path for branch and predicate plumbing.",
    ),
    (
        "ENC_SOPK",
        "S_MOVK_I32",
        "Small scalar-immediate surface used by early control kernels.",
    ),
    (
        "ENC_SMEM",
        "S_LOAD_B32",
        "RDNA4 scalar memory is a first architecture-local blocker.",
    ),
    (
        "ENC_VOP1",
        "V_MOV_B32",
        "Vector move and conversion baseline reused across many programs.",
    ),
    (
        "ENC_VOP2",
        "V_ADD_F32",
        "Core vector arithmetic used by both compute and graphics paths.",
    ),
    (
        "ENC_VOPC",
        "V_CMP_EQ_F32",
        "Vector compare path for control, masking, and shader predicates.",
    ),
    (
        "ENC_VOP3",
        "V_ADD3_U32",
        "Largest instruction family and the main overlap with gfx950 precedent.",
    ),
    (
        "ENC_VDS",
        "DS_ADD_U32",
        "LDS data path with a small fully-supported carry-over subset.",
    ),
    (
        "ENC_VGLOBAL",
        "GLOBAL_LOAD_B32",
        "Global memory load/store family that replaces gfx950-specific naming.",
    ),
]

ROLLUP_ENUM = {
    "transferable_as_is": "Gfx1201SupportRollup::kTransferableAsIs",
    "transferable_with_decoder_work": "Gfx1201SupportRollup::kTransferableWithDecoderWork",
    "transferable_with_semantic_work": "Gfx1201SupportRollup::kTransferableWithSemanticWork",
    "gfx1201_specific": "Gfx1201SupportRollup::kGfx1201Specific",
}

STATE_ENUM = {
    "transferable_as_is": "Gfx1201SupportState::kTransferableAsIs",
    "transferable_with_decoder_work": "Gfx1201SupportState::kTransferableWithDecoderWork",
    "transferable_with_semantic_work": "Gfx1201SupportState::kTransferableWithSemanticWork",
    "transferable_with_decoder_and_semantic_work": (
        "Gfx1201SupportState::kTransferableWithDecoderAndSemanticWork"
    ),
    "gfx1201_specific": "Gfx1201SupportState::kGfx1201Specific",
}


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def cxx_string(value: str) -> str:
    return json.dumps(value)


def cxx_bool(value: bool) -> str:
    return "true" if value else "false"


def state_sort_key(value: str) -> int:
    return STATE_ORDER.index(value)


def render_decoder_seed_cc(report: dict) -> str:
    entries = report["entries"]
    encodings = report["encodings"]
    lines = [
        '#include "lib/sim/isa/gfx1201/decoder_seed.h"',
        "",
        "#include <array>",
        "",
        "namespace mirage::sim::isa {",
        "namespace {",
        "",
        "// Generated by tools/architecture_import/gfx1201/generate_gfx1201_decoder_seed.py",
        f"constexpr std::array<Gfx1201DecoderSeedEntry, {len(entries)}> kSeedEntries{{{{",
    ]

    for entry in entries:
        lines.append(
            f"    {{{cxx_string(entry['instruction_name'])}, "
            f"{cxx_string(entry['encoding_name'])}, "
            f"{cxx_string(entry['encoding_condition'])}, {entry['opcode']}u, "
            f"{entry['operand_count']}u, {ROLLUP_ENUM[entry['rollup']]}, "
            f"{STATE_ENUM[entry['state']]}, {cxx_bool(entry['is_default_encoding'])}}},"
        )

    lines.extend(
        [
            "}};",
            "",
            f"constexpr std::array<Gfx1201DecoderSeedEncoding, {len(encodings)}> kSeedEncodings{{{{",
        ]
    )

    for encoding in encodings:
        lines.append(
            f"    {{{cxx_string(encoding['encoding_name'])}, "
            f"{cxx_string(encoding['example_instruction'])}, "
            f"{cxx_string(encoding['rationale'])}, {encoding['instruction_count']}u, "
            f"{encoding['entry_begin']}u, {encoding['entry_count']}u, "
            f"{encoding['default_entry_count']}u, {encoding['alternate_entry_count']}u, "
            f"{encoding['transferable_as_is_count']}u, "
            f"{encoding['transferable_with_decoder_work_count']}u, "
            f"{encoding['transferable_with_semantic_work_count']}u, "
            f"{encoding['transferable_with_decoder_and_semantic_work_count']}u, "
            f"{encoding['gfx1201_specific_count']}u}},"
        )

    lines.extend(
        [
            "}};",
            "",
            "}  // namespace",
            "",
            "std::span<const Gfx1201DecoderSeedEncoding>",
            "GetGfx1201Phase0ComputeDecoderSeeds() {",
            "  return kSeedEncodings;",
            "}",
            "",
            "const Gfx1201DecoderSeedEncoding* FindGfx1201Phase0ComputeDecoderSeed(",
            "    std::string_view encoding_name) {",
            "  for (const Gfx1201DecoderSeedEncoding& encoding : kSeedEncodings) {",
            "    if (encoding.encoding_name == encoding_name) {",
            "      return &encoding;",
            "    }",
            "  }",
            "  return nullptr;",
            "}",
            "",
            "std::span<const Gfx1201DecoderSeedEntry> GetGfx1201Phase0ComputeDecoderSeedEntries() {",
            "  return kSeedEntries;",
            "}",
            "",
            "std::span<const Gfx1201DecoderSeedEntry> GetGfx1201Phase0ComputeDecoderSeedEntries(",
            "    const Gfx1201DecoderSeedEncoding& encoding) {",
            "  return std::span<const Gfx1201DecoderSeedEntry>(",
            "      kSeedEntries.data() + encoding.entry_begin, encoding.entry_count);",
            "}",
            "",
            "bool IsGfx1201Phase0ComputeEncoding(std::string_view encoding_name) {",
            "  return FindGfx1201Phase0ComputeDecoderSeed(encoding_name) != nullptr;",
            "}",
            "",
            "}  // namespace mirage::sim::isa",
            "",
        ]
    )
    return "\n".join(lines)


def render_markdown(report: dict) -> str:
    lines = [
        "# gfx1201 Phase-0 Compute Decoder Seed",
        "",
        "## Scope",
        "",
        "- Seeded encoding families: `ENC_SOPP`, `ENC_SOP1`, `ENC_SOP2`, `ENC_SOPC`, `ENC_SOPK`, `ENC_SMEM`, `ENC_VOP1`, `ENC_VOP2`, `ENC_VOPC`, `ENC_VOP3`, `ENC_VDS`, `ENC_VGLOBAL`",
        f"- Unique seeded instructions: `{report['summary']['unique_instruction_count']}`",
        f"- Seeded decode entries: `{report['summary']['entry_count']}`",
        "",
        "## Encoding Seeds",
        "",
        (
            "- `transferable_with_decoder_work` below is exact decoder-only work; "
            "`transferable_with_decoder_and_semantic_work` is listed separately."
        ),
        "",
    ]

    for encoding in report["encodings"]:
        lines.extend(
            [
                f"### {encoding['encoding_name']}",
                "",
                f"- Example instruction: `{encoding['example_instruction']}`",
                f"- Rationale: {encoding['rationale']}",
                f"- Unique instructions: `{encoding['instruction_count']}`",
                f"- Seed entries: `{encoding['entry_count']}` (`default={encoding['default_entry_count']}`, `alternate={encoding['alternate_entry_count']}`)",
                (
                    f"- Support split: as-is `{encoding['transferable_as_is_count']}`, "
                    f"decoder-only `{encoding['transferable_with_decoder_work_count']}`, "
                    f"semantic-only `{encoding['transferable_with_semantic_work_count']}`, "
                    f"decoder+semantic `{encoding['transferable_with_decoder_and_semantic_work_count']}`, "
                    f"gfx1201-specific `{encoding['gfx1201_specific_count']}`"
                ),
                (
                    "- Sample worklist: "
                    f"as-is {', '.join(f'`{name}`' for name in encoding['samples']['transferable_as_is']) or 'None'}, "
                    f"decoder-only {', '.join(f'`{name}`' for name in encoding['samples']['transferable_with_decoder_work']) or 'None'}, "
                    f"semantic-only {', '.join(f'`{name}`' for name in encoding['samples']['transferable_with_semantic_work']) or 'None'}, "
                    f"decoder+semantic {', '.join(f'`{name}`' for name in encoding['samples']['transferable_with_decoder_and_semantic_work']) or 'None'}, "
                    f"gfx1201-specific {', '.join(f'`{name}`' for name in encoding['samples']['gfx1201_specific']) or 'None'}"
                ),
                "",
            ]
        )

    return "\n".join(lines) + "\n"


def main() -> int:
    if not SUPPORT_MATRIX_PATH.exists():
        raise RuntimeError(
            "missing gfx1201 support matrix; run "
            "generate_gfx1201_support_catalog.py first"
        )

    inventory = read_json(INVENTORY_PATH)
    support_matrix = read_json(SUPPORT_MATRIX_PATH)
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    DECODER_SEED_CC_PATH.parent.mkdir(parents=True, exist_ok=True)

    support_by_name = {
        item["instruction_name"]: item for item in support_matrix["instructions"]
    }
    inventory_by_name = {
        item["instruction_name"]: item for item in inventory["instructions"]
    }

    entries = []
    encodings = []
    seen_instruction_names: set[str] = set()
    for encoding_name, example_instruction, rationale in PHASE0_ENCODINGS:
        if example_instruction not in inventory_by_name:
            raise RuntimeError(f"missing representative instruction: {example_instruction}")

        matching_instructions = []
        for instruction in inventory["instructions"]:
            matching_entries = [
                encoding
                for encoding in instruction["encodings"]
                if encoding["encoding_name"] == encoding_name
            ]
            if not matching_entries:
                continue
            support = support_by_name[instruction["instruction_name"]]
            matching_instructions.append((instruction, support, matching_entries))

        if not matching_instructions:
            raise RuntimeError(f"no matching instructions for {encoding_name}")

        entry_begin = len(entries)
        state_counts = Counter()
        samples = {state: [] for state in STATE_ORDER}
        instruction_names = set()
        default_entry_count = 0
        alternate_entry_count = 0

        local_entries = []
        for instruction, support, matching_entries in matching_instructions:
            instruction_name = instruction["instruction_name"]
            instruction_names.add(instruction_name)
            seen_instruction_names.add(instruction_name)
            state = support["state"]
            state_counts[state] += 1
            if len(samples[state]) < 4:
                samples[state].append(instruction_name)

            for encoding in matching_entries:
                is_default = encoding["encoding_condition"] == "default"
                if is_default:
                    default_entry_count += 1
                else:
                    alternate_entry_count += 1
                local_entries.append(
                    {
                        "instruction_name": instruction_name,
                        "encoding_name": encoding_name,
                        "encoding_condition": encoding["encoding_condition"],
                        "opcode": encoding["opcode"],
                        "operand_count": encoding["operand_count"],
                        "rollup": support["rollup"],
                        "state": state,
                        "is_default_encoding": is_default,
                    }
                )

        local_entries.sort(
            key=lambda item: (
                state_sort_key(item["state"]),
                item["instruction_name"],
                not item["is_default_encoding"],
                item["encoding_condition"],
                item["opcode"],
            )
        )
        entries.extend(local_entries)

        encodings.append(
            {
                "encoding_name": encoding_name,
                "example_instruction": example_instruction,
                "rationale": rationale,
                "instruction_count": len(instruction_names),
                "entry_begin": entry_begin,
                "entry_count": len(local_entries),
                "default_entry_count": default_entry_count,
                "alternate_entry_count": alternate_entry_count,
                "transferable_as_is_count": state_counts["transferable_as_is"],
                "transferable_with_decoder_work_count": state_counts[
                    "transferable_with_decoder_work"
                ],
                "transferable_with_semantic_work_count": state_counts[
                    "transferable_with_semantic_work"
                ],
                "transferable_with_decoder_and_semantic_work_count": state_counts[
                    "transferable_with_decoder_and_semantic_work"
                ],
                "gfx1201_specific_count": state_counts["gfx1201_specific"],
                "samples": samples,
            }
        )

    report = {
        "summary": {
            "encoding_count": len(encodings),
            "unique_instruction_count": len(seen_instruction_names),
            "entry_count": len(entries),
        },
        "encodings": encodings,
        "entries": entries,
    }

    REPORT_JSON_PATH.write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    REPORT_MD_PATH.write_text(render_markdown(report), encoding="utf-8")
    DECODER_SEED_CC_PATH.write_text(render_decoder_seed_cc(report), encoding="utf-8")

    print(f"Wrote {REPORT_JSON_PATH.relative_to(MIRAGE_ROOT)}")
    print(f"Wrote {REPORT_MD_PATH.relative_to(MIRAGE_ROOT)}")
    print(f"Wrote {DECODER_SEED_CC_PATH.relative_to(MIRAGE_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
