name: Build Linux PyTorch Wheels

on:
  workflow_call:
    inputs:
      AMDGPU_FAMILIES:
        required: true
        type: string
      PYTORCH_TARGET_ARCH:
        required: true
        type: string
      python_version:
        required: true
        type: string
      find_links:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      AMDGPU_FAMILIES:
        required: true
        type: string
      PYTORCH_TARGET_ARCH:
        required: true
        type: string
      python_version:
        required: true
        type: string
      find_links:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build_pytorch_wheels:
    name: Build Linux PyTorch Wheels | ${{ inputs.AMDGPU_FAMILIES }} | Python ${{ inputs.python_version }}
    runs-on: ${{ github.repository_owner == 'ROCm' && 'azure-linux-scale-rocm' || 'ubuntu-24.04' }}
    container:
      image: ghcr.io/rocm/therock_build_manylinux_x86_64:main
    env:
      OUTPUT_DIR: ${{ github.workspace }}/output
      PACKAGE_DIST_DIR: ${{ github.workspace }}/output/packages/dist
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure Git Identity
        run: |
          git config --global user.name "therockbot"
          git config --global user.email "therockbot@amd.com"

      - name: Checkout PyTorch Source Repos
        run: |
          echo "Checking out PyTorch repositories..."
          ./external-builds/pytorch/pytorch_torch_repo.py checkout
          ./external-builds/pytorch/pytorch_audio_repo.py checkout
          ./external-builds/pytorch/pytorch_vision_repo.py checkout

      - name: Create pip cache directory
        run: mkdir -p /tmp/pipcache

      - name: Build PyTorch Wheels
        run: |
          echo "Building PyTorch wheels for ${{ inputs.PYTORCH_TARGET_ARCH }}"
          ./external-builds/pytorch/build_prod_wheels.py \
            --pip-cache-dir /tmp/pipcache \
            --find-links "${{ inputs.find_links }}" \
            build \
            --install-rocm \
            --clean \
            --output-dir ${{ env.PACKAGE_DIST_DIR }} \
            --pytorch-rocm-arch ${{ inputs.PYTORCH_TARGET_ARCH }} \

      - name: Configure AWS Credentials
        if: always()
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::692859939525:role/therock-nightly-releases

      - name: Sanity Check Wheel
        run: |
          python external-builds/pytorch/sanity_check_wheel.py ${{ env.PACKAGE_DIST_DIR }}/

      - name: Upload wheels to S3
        if: ${{ github.repository_owner == 'ROCm' }}
        run: |
          # These wheels share the same S3 directory as rocm-sdk to simplify --find-links usage
          aws s3 cp ${{ env.PACKAGE_DIST_DIR }}/ s3://therock-nightly-python/${{ inputs.AMDGPU_FAMILIES }}/ \
            --recursive --exclude "*" --include "*.whl"
