name: Build Linux JAX from TheRock tarball

on:
  workflow_call:
    inputs:
      amdgpu_family:
        type: string
        required: true
      package_version:
        type: string
        required: true
      release_type:
        type: string
        required: true
      tarball_url:
        type: string
        required: true

jobs:
  build_jax:
    name: Build JAX wheels | ${{ inputs.amdgpu_family }}
    uses: ./.github/workflows/build_linux_jax_wheels.yml
    permissions:
      contents: read
      id-token: write
      packages: read
    secrets: inherit
    with:
      amdgpu_family: ${{ inputs.amdgpu_family }}
      python_version: "3.12"
      release_type: ${{ inputs.release_type }}
      s3_subdir: "v2"
      s3_staging_subdir: "v2-staging"
      rocm_version: ${{ inputs.package_version }}
      tar_url: ${{ inputs.tarball_url }}
      run_tests: false
      upload_wheels: false
