name: Build PyTorch Docker

on:
  workflow_call:
    inputs:
      torch_version:
        description: Torch version to install inside the docker image
        required: true
        type: string
      python_version:
        description: Python version to use in the docker image (e.g., 3.12)
        required: true
        type: string
      rocm_version:
        description: ROCm version to install inside the docker image (e.g., 7.9)
        required: true
        type: string
      package_index_url:
        description: Base URL for the Python package index (e.g., CloudFront release/staging URL)
        required: true
        type: string
      amdgpu_family:
        description: AMD GPU family to select the wheel index subdir (e.g., gfx94X-dcgpu)
        required: true
        type: string
      push:
        description: Whether to push the built image to Docker Hub
        required: false
        type: boolean
        default: true
      repository:
        description: "Repository to checkout. Defaults to caller repo."
        required: false
        type: string
        default: ""
      ref:
        description: "Branch, tag or SHA to checkout. Defaults to the same ref as the caller."
        required: false
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      torch_version:
        type: string
        required: true
      python_version:
        type: string
        required: true
        default: "3.12"
      rocm_version:
        type: string
        required: true
        default: "7.9"
      package_index_url:
        type: string
        required: true
        default: "https://d25kgig7rdsyks.cloudfront.net/v2"
      amdgpu_family:
        type: string
        required: true
        default: "gfx94X-dcgpu"
      push:
        type: boolean
        default: true
      repository:
        type: string
        default: ""
      ref:
        type: string
        default: ""

permissions:
  contents: read

jobs:
  build:
    name: Build PyTorch Docker Image
    runs-on: ubuntu-24.04
    env:
      TORCH_VERSION: ${{ inputs.torch_version }}
      PYTHON_VERSION: ${{ inputs.python_version }}
      ROCM_VERSION: ${{ inputs.rocm_version }}
      PACKAGE_INDEX_URL: ${{ inputs.package_index_url }}
      AMDGPU_FAMILY: ${{ inputs.amdgpu_family }}
    steps:
      - name: Checkout same repo/ref as caller
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.ref }}

      - name: Compute image tag
        id: dockertag
        run: |
          safe() { echo "$1" | tr '[:upper:]' '[:lower:]' | tr '/ +' '_' ; }
          ROCM_TAG="$(safe "${ROCM_VERSION}")"
          TORCH_TAG="$(safe "${TORCH_VERSION}")"
          VERSION_TAG="${ROCM_TAG}${TORCH_TAG}"
          IMAGE_NAME="rocm/pytorch-private"
          FULL_TAG="${IMAGE_NAME}:${VERSION_TAG}"
          echo "full_tag=$FULL_TAG" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        if: ${{ inputs.push }}
        uses: docker/login-action@343f7c4bf00b1f00bd204f3ebc5f52cf49bbaadf # v3.2.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@2a1a44b732b0f7cf5c4f40437c61a375661ce323 # v3.7.1

      - name: Build and push image
        uses: docker/build-push-action@4a4aa73e2adbb7b574b7c67b0e5b5616f9dc5381 # v6.9.0
        with:
          context: .
          file: TheRock/dockerfiles/pytorch_base.Dockerfile
          push: ${{ inputs.push }}
          tags: |
            ${{ steps.dockertag.outputs.full_tag }}
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            TORCH_VERSION=${{ env.TORCH_VERSION }}
            ROCM_VERSION=${{ env.ROCM_VERSION }}
            PACKAGE_INDEX_URL=${{ env.PACKAGE_INDEX_URL }}
            AMDGPU_FAMILY=${{ env.AMDGPU_FAMILY }}

      - name: Summary
        run: |
          echo "Built image: ${{ steps.dockertag.outputs.full_tag }}"
          echo "Python: $PYTHON_VERSION"
          echo "Torch: $TORCH_VERSION"
          echo "ROCm: $ROCM_VERSION"
          echo "Index: $PACKAGE_INDEX_URL"
          echo "Family: $AMDGPU_FAMILY"
