name: Build Linux PyTorch Wheels

on:
  workflow_call:
    inputs:
      family:
        required: true
        type: string
      target:
        required: true
        type: string
      python_version:
        required: true
        type: string
      find_links:
        required: true
        type: string
      version_suffix:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build_pytorch_wheels:
    name: Build PyTorch Wheels | ${{ inputs.family }} | Python ${{ inputs.python_version }}
    runs-on: ${{ github.repository_owner == 'ROCm' && 'azure-linux-scale-rocm' || 'ubuntu-24.04' }}
    container:
      image: ghcr.io/rocm/therock_build_manylinux_x86_64:main
    env:
      OUTPUT_DIR: /__w/TheRock/TheRock/output
      PACKAGE_DIST_DIR: /__w/TheRock/TheRock/output/packages/dist
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure Git Identity
        run: |
          git config --global user.name "no-body"
          git config --global user.email "nobody@amd.com"

      - name: Checkout PyTorch Source Repos
        run: |
          echo "Checking out PyTorch repositories..."
          ./external-builds/pytorch/pytorch_torch_repo.py checkout
          ./external-builds/pytorch/pytorch_audio_repo.py checkout
          ./external-builds/pytorch/pytorch_vision_repo.py checkout

      - name: Build PyTorch Wheels
        run: |
          echo "Building PyTorch wheels for ${{ inputs.target }}"
          ./external-builds/pytorch/build_prod_wheels.py build \
            --find-links "https://therock-nightly-python.s3.us-east-2.amazonaws.com/${{ inputs.family }}/index.html" \
            --install-rocm \
            --clean \
            --output-dir ${{ env.PACKAGE_DIST_DIR }} \
            --pytorch-rocm-arch ${{ inputs.target }} \
            --version-suffix "+rocmsdk${{ inputs.version_suffix }}"

      - name: Sanity Check Wheel
        run: |
          python external-builds/pytorch/sanity_check_wheel.py ${{ env.PACKAGE_DIST_DIR }}/

      - name: Upload wheels to S3
        if: ${{ github.repository_owner == 'ROCm' }}
        run: |
          # These wheels share the same S3 directory as rocm-sdk to simplify --find-links usage
          aws s3 cp ${{ env.PACKAGE_DIST_DIR }}/ s3://therock-nightly-python/${{ inputs.family }}/ \
            --recursive --exclude "*" --include "*.whl"
