name: Build Windows PyTorch Wheels

on:
  workflow_call:
    inputs:
      AMDGPU_FAMILIES:
        required: true
        type: string
      python_version:
        required: true
        type: string
      s3_bucket:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      AMDGPU_FAMILIES:
        required: true
        type: string
      python_version:
        required: true
        type: string
      s3_bucket:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build_pytorch_wheels:
    name: Build Windows PyTorch Wheels | ${{ inputs.AMDGPU_FAMILIES }} | Python ${{ inputs.python_version }}
    runs-on: ${{ github.repository_owner == 'ROCm' && 'azure-windows-scale-rocm' || 'windows-2022' }}
    env:
      OUTPUT_DIR: ${{ github.workspace }}/output
      PACKAGE_DIST_DIR: ${{ github.workspace }}/output/packages/dist
      S3_BUCKET: ${{ inputs.s3_bucket }}
      S3_ENDPOINT: "s3.us-east-2.amazonaws.com"
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure Git Identity
        run: |
          git config --global user.name "therockbot"
          git config --global user.email "therockbot@amd.com"

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ inputs.python_version }}

      - name: Checkout PyTorch Source Repos
        run: |
          python ./external-builds/pytorch/pytorch_torch_repo.py checkout
      # TODO(scotttodd): include these
          # python ./external-builds/pytorch/pytorch_audio_repo.py checkout
          # python ./external-builds/pytorch/pytorch_vision_repo.py checkout

      # TODO(scotttodd): build wheels, put into a directory location for next step to use

      # TODO(scotttodd): add upload once working

      # - name: Upload wheels to S3
      #   if: ${{ github.repository_owner == 'ROCm' }}
      #   run: |
      #     aws s3 cp ${{ env.PACKAGE_DIST_DIR }}/ s3://${{ env.S3_BUCKET }}/${{ inputs.AMDGPU_FAMILIES }}/ \
      #       --recursive --exclude "*" --include "*.whl"

      # - name: (Re-)Generate Python package release index
      #   if: ${{ github.repository_owner == 'ROCm' }}
      #   run: |
      #     pip install boto3
      #     python ./build_tools/packaging/python/generate_release_index.py \
      #       --bucket=${{ env.S3_BUCKET }} \
      #       --endpoint=${{ env.S3_ENDPOINT }} \
      #       --subdir=${{ inputs.AMDGPU_FAMILIES }} \
      #       --output=${{ github.workspace }}/index.html
      #     aws s3 cp ${{ github.workspace }}/index.html s3://${{ env.S3_BUCKET }}/${{ inputs.AMDGPU_FAMILIES }}/
