name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_linux_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Linux GPU families to build. ex: gfx94X, gfx1201X"
        default: ""
      build_windows_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Windows GPU families to build. ex: gfx94X, gfx1201X"
        default: ""
      test_linux_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Linux GPU families to test. ex: gfx94X, gfx1201X"
        default: ""
      test_windows_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Windows GPU families to test. ex: gfx94X, gfx1201X"
        default: ""
      artifact_run_id:
        type: string
        description: "If provided, the tests will run on this artifact ID"
        default: ""
  pull_request:
    types:
      - labeled
      - opened
      - synchronize

permissions:
  contents: read

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  build_linux_packages:
    name: Build Linux Packages
    needs: setup
    if: ${{ needs.setup.outputs.build_linux_amdgpu_families != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        families: ${{ fromJSON(needs.setup.outputs.build_linux_amdgpu_families) }}
    uses: ./.github/workflows/build_linux_packages.yml
    with:
      amdgpu_families: ${{ matrix.families.target }}
    permissions:
      id-token: write

  build_windows_packages:
    name: Build Windows Packages
    needs: setup
    if: ${{ needs.setup.outputs.build_windows_amdgpu_families != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        families: ${{ fromJSON(needs.setup.outputs.build_windows_amdgpu_families) }}
    uses: ./.github/workflows/build_windows_packages.yml
    with:
      amdgpu_families: ${{ matrix.families.target }}

  test_linux_packages:
    needs: [setup, build_linux_packages]
    name: Test Linux Packages
    # If there are no linux_amdgpu_families to test or a dependent job failed/cancelled, this job will not be run
    if: >-
      ${{
        !failure() &&
        !cancelled() &&
        needs.setup.outputs.test_linux_amdgpu_families != '[]'
      }}
    strategy:
      fail-fast: false
      matrix:
        families: ${{ fromJSON(needs.setup.outputs.test_linux_amdgpu_families) }}
    uses: ./.github/workflows/test_linux_packages.yml
    with:
      amdgpu_families: ${{ matrix.families.target }}
      test_runs_on: ${{ matrix.families.test-runs-on }}
      artifact_run_id: ${{ inputs.artifact_run_id }}

  # build_python_packages:
  #   name: Build Python Packages
  #   uses: ./.github/workflows/build_python_packages.yml
