name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      linux_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Linux GPU families to build and test. ex: gfx94X, gfx1201X"
        default: ""
      run_linux_tests_only:
        type: boolean
        description: "If run_linux_tests_only is enabled, the CI will pull linux artifacts using artifact_run_id and only run tests"
      windows_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Windows GPU families to build and test. ex: gfx94X, gfx1201X"
        default: ""
      run_windows_tests_only:
        type: boolean
        description: "If run_windows_tests_only is enabled, the CI will pull windows artifacts using artifact_run_id and only run tests"
      artifact_run_id:
        type: string
        description: "If provided, the tests will run on this artifact ID"
        default: ""
  pull_request:
    types:
      - labeled
      - opened
      - synchronize

permissions:
  contents: read

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  linux_build_and_test:
    name: Build And Test Linux Packages
    needs: setup
    if: >-
      ${{
        needs.setup.outputs.linux_amdgpu_families != '[]' &&
        needs.setup.outputs.enable_build_jobs == 'true'
      }}
    strategy:
      fail-fast: false
      matrix:
        families: ${{ fromJSON(needs.setup.outputs.linux_amdgpu_families) }}
    uses: ./.github/workflows/linux_build_and_test.yml
    with:
      amdgpu_families: ${{ matrix.families.family }}
      test_runs_on: ${{ matrix.families.test-runs-on }}
      artifact_run_id: ${{ inputs.artifact_run_id }}
      run_linux_tests_only: ${{ inputs.run_linux_tests_only == 'true' && 'true' || 'false' }}
    permissions:
      id-token: write

  build_windows_packages:
    name: Build Windows Packages
    needs: setup
    if: >-
      ${{
        needs.setup.outputs.windows_amdgpu_families != '[]' &&
        needs.setup.outputs.enable_build_jobs == 'true'
      }}
    strategy:
      fail-fast: false
      matrix:
        families: ${{ fromJSON(needs.setup.outputs.windows_amdgpu_families) }}
    uses: ./.github/workflows/build_windows_packages.yml
    with:
      amdgpu_families: ${{ matrix.families.family }}

  # build_python_packages:
  #   name: Build Python Packages
  #   uses: ./.github/workflows/build_python_packages.yml
