name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      linux_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Linux GPU families. ex: gfx94X, gfx1201X"
        default: "gfx94X"
      windows_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Windows GPU families. ex: gfx94X, gfx1201X"
        default: "gfx94X"
  pull_request:
    types:
      - labeled
      - opened

permissions:
  contents: read

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      linux_amdgpu_families: ${{ inputs.linux_amdgpu_families }}
      windows_amdgpu_families: ${{ inputs.windows_amdgpu_families }}

  build_linux_packages:
    name: Build Linux Packages
    needs: setup
    if: ${{ fromJSON(needs.setup.outputs.enable_build_jobs) || needs.setup.outputs.linux_amdgpu_families != '[]' }}
    strategy:
      matrix:
        families: ${{ fromJSON(needs.setup.outputs.linux_amdgpu_families) }}
    uses: ./.github/workflows/build_linux_packages.yml
    with:
      amdgpu_families: ${{ matrix.families.target }}
    permissions:
      id-token: write

  build_windows_packages:
    name: Build Windows Packages
    needs: setup
    if: ${{ fromJSON(needs.setup.outputs.enable_build_jobs) || needs.setup.outputs.windows_amdgpu_families != '[]' }}
    strategy:
      matrix:
        families: ${{ fromJSON(needs.setup.outputs.windows_amdgpu_families) }}
    uses: ./.github/workflows/build_windows_packages.yml
    with:
      amdgpu_families: ${{ matrix.families.target }}

  test_linux_packages:
    needs: [setup, build_linux_packages]
    name: Test Linux Packages
    if: ${{ needs.setup.outputs.linux_amdgpu_families != '[]' }}
    strategy:
      matrix:
        families: ${{ fromJSON(needs.setup.outputs.linux_amdgpu_families) }}
    uses: ./.github/workflows/test_linux_packages.yml
    with:
      amdgpu_families: ${{ matrix.families.target }}
      test_runs_on: ${{ matrix.families.test-runs-on }}

  # build_python_packages:
  #   name: Build Python Packages
  #   uses: ./.github/workflows/build_python_packages.yml
