# This CI workflow is triggered by:
#   - scheduled run
#
# In the scheduled run, we run all targets from amdgpu_family_matrix.py and amdgpu_family_matrix_xfail.py
# As some of these builds are xfail, we allow errors to occur with `continue-on-error`, where the job will fail but the workflow is green

name: CI Nightly

on:
  # For AMD GPU families that expect_failure, we run builds and tests from this scheduled trigger
  schedule:
    - cron: "0 2 * * *" # Runs nightly at 2 AM UTC
  workflow_dispatch:
    inputs:
      linux_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Linux GPU families to build and test. ex: gfx94X, gfx1201X"
        default: ""
      linux_test_labels:
        type: string
        description: "If enabled, reduce test set on Linux to the list of labels prefixed with 'test:'"
        default: ""
      linux_use_prebuilt_artifacts:
        type: boolean
        description: "If enabled, the CI will pull Linux artifacts using artifact_run_id and only run tests"
      windows_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Windows GPU families to build and test. ex: gfx94X, gfx1201X"
        default: ""
      windows_test_labels:
        type: string
        description: "If enabled, reduce test set on Windows to the list of labels prefixed with 'test:'"
        default: ""
      windows_use_prebuilt_artifacts:
        type: boolean
        description: "If enabled, the CI will pull Windows artifacts using artifact_run_id and only run tests"
      artifact_run_id:
        type: string
        description: "If provided, the tests will run on this artifact ID"
        default: ""

permissions:
  contents: read

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  linux_build_and_test:
    name: Linux::${{ matrix.variant.family }}::${{ matrix.variant.build_variant_label }}
    needs: setup
    if: >-
      ${{
        needs.setup.outputs.linux_variants != '[]' &&
        needs.setup.outputs.enable_build_jobs == 'true'
      }}
    strategy:
      fail-fast: false
      matrix:
        variant: ${{ fromJSON(needs.setup.outputs.linux_variants) }}
    uses: ./.github/workflows/ci_linux.yml
    secrets: inherit
    with:
      amdgpu_families: ${{ matrix.variant.family }}
      artifact_group: ${{ matrix.variant.artifact_group }}
      test_runs_on: ${{ matrix.variant.test-runs-on }}
      build_variant_label: ${{ matrix.variant.build_variant_label }}
      build_variant_suffix: ${{ matrix.variant.build_variant_suffix }}
      build_variant_cmake_preset: ${{ matrix.variant.build_variant_cmake_preset }}
      test_labels: ${{ needs.setup.outputs.linux_test_labels }}
      artifact_run_id: ${{ inputs.artifact_run_id }}
      expect_failure: ${{ matrix.variant.expect_failure == true }}
      use_prebuilt_artifacts: ${{ inputs.linux_use_prebuilt_artifacts == true && 'true' || 'false' }}
      rocm_package_version: ${{ needs.setup.outputs.rocm_package_version }}
      test_type: ${{ needs.setup.outputs.test_type }}
      sanity_check_only_for_family: ${{ matrix.variant.sanity_check_only_for_family == true }}
    permissions:
      contents: read
      id-token: write

  windows_build_and_test:
    name: Windows::${{ matrix.variant.family }}::${{ matrix.variant.build_variant_label }}
    needs: setup
    if: >-
      ${{
        needs.setup.outputs.windows_variants != '[]' &&
        needs.setup.outputs.enable_build_jobs == 'true'
      }}
    strategy:
      fail-fast: false
      matrix:
        variant: ${{ fromJSON(needs.setup.outputs.windows_variants) }}
    uses: ./.github/workflows/ci_windows.yml
    with:
      amdgpu_families: ${{ matrix.variant.family }}
      artifact_group: ${{ matrix.variant.artifact_group }}
      test_runs_on: ${{ matrix.variant.test-runs-on }}
      build_variant_label: ${{ matrix.variant.build_variant_label }}
      build_variant_suffix: ${{ matrix.variant.build_variant_suffix }}
      build_variant_cmake_preset: ${{ matrix.variant.build_variant_cmake_preset }}
      test_labels: ${{ needs.setup.outputs.windows_test_labels }}
      artifact_run_id: ${{ inputs.artifact_run_id }}
      expect_failure: ${{ matrix.variant.expect_failure == true }}
      use_prebuilt_artifacts: ${{ inputs.windows_use_prebuilt_artifacts == true && 'true' || 'false' }}
      rocm_package_version: ${{ needs.setup.outputs.rocm_package_version }}
      test_type: ${{ needs.setup.outputs.test_type }}
      sanity_check_only_for_family: ${{ matrix.variant.sanity_check_only_for_family == true }}
    permissions:
      contents: read
      id-token: write

  # build_python_packages:
  #   name: Build Python Packages
  #   uses: ./.github/workflows/build_python_packages.yml

  aggregate_and_push_to_loki:
    name: "Aggregate all CI logs and push to Loki"
    if: always()
    runs-on: ubuntu-latest
    needs: [linux_build_and_test, windows_build_and_test]

    steps:
      - name: Download all logs from Linux and Windows jobs
        uses: actions/download-artifact@v4
        with:
          path: ./aggregated_logs

      - name: Aggregate all logs and outcomes
        run: |
          echo "CI Nightly Aggregated Report" > ci_summary.txt
          echo "--------------------------------------" >> ci_summary.txt
          echo "Workflow: ${{ github.workflow }}" >> ci_summary.txt
          echo "Run ID: ${{ github.run_id }}" >> ci_summary.txt
          echo "Run Number: ${{ github.run_number }}" >> ci_summary.txt
          echo "Repository: ${{ github.repository }}" >> ci_summary.txt
          echo "Commit: ${{ github.sha }}" >> ci_summary.txt
          echo "Trigger: ${{ github.event_name }}" >> ci_summary.txt
          echo "Timestamp: $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> ci_summary.txt
          echo "" >> ci_summary.txt

          echo "--------------------------------------" >> ci_summary.txt
          echo "Linux Configuration:" >> ci_summary.txt
          echo "  AMD GPU Families: ${{ inputs.linux_amdgpu_families || 'N/A' }}" >> ci_summary.txt
          echo "  Test Labels: ${{ inputs.linux_test_labels || 'N/A' }}" >> ci_summary.txt
          echo "  Using Prebuilt Artifacts: ${{ inputs.linux_use_prebuilt_artifacts }}" >> ci_summary.txt
          echo "" >> ci_summary.txt

          echo "Windows Configuration:" >> ci_summary.txt
          echo "  AMD GPU Families: ${{ inputs.windows_amdgpu_families || 'N/A' }}" >> ci_summary.txt
          echo "  Test Labels: ${{ inputs.windows_test_labels || 'N/A' }}" >> ci_summary.txt
          echo "  Using Prebuilt Artifacts: ${{ inputs.windows_use_prebuilt_artifacts }}" >> ci_summary.txt
          echo "" >> ci_summary.txt

          echo "--------------------------------------" >> ci_summary.txt
          echo "Job Results Summary:" >> ci_summary.txt
          echo "--------------------------------------" >> ci_summary.txt
          echo "All Linux Jobs Passing? : ${{ needs.linux_build_and_test.result }}" >> ci_summary.txt
          echo "All Windows Jobs Passing? : ${{ needs.windows_build_and_test.result }}" >> ci_summary.txt
          echo "" >> ci_summary.txt
          echo "Detailed Logs Found:" >> ci_summary.txt
          find ./aggregated_logs -type f -name "*.log" >> ci_summary.txt || echo "No detailed logs found" >> ci_summary.txt

          # Optionally compress logs for reference
          tar -czf ci_logs_bundle.tar.gz ./aggregated_logs || true

      - name: Upload aggregated report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-nightly-summary
          path: |
            ci_summary.txt
            ci_logs_bundle.tar.gz
          retention-days: 7

      - name: Send CI summary to Loki
        env:
          LOKI_URL: ${{ secrets.LOKI_URL }}
          LOKI_USER: ${{ secrets.LOKI_USER }}
          LOKI_PASS: ${{ secrets.LOKI_PASS }}
        run: |
          echo "Pushing CI Nightly summary to Loki..."
          LOG_CONTENT=$(cat ci_summary.txt | jq -Rs .)
          TIMESTAMP=$(date +%s%N)
          curl -u "$LOKI_USER:$LOKI_PASS" -X POST -H "Content-Type: application/json" \
            -d "{
              \"streams\": [
                {
                  \"stream\": {
                    \"job\": \"ci_nightly\",
                    \"repo\": \"${{ github.repository }}\",
                    \"workflow\": \"${{ github.workflow }}\",
                    \"run_id\": \"${{ github.run_id }}\"
                  },
                  \"values\": [[\"$TIMESTAMP\", $LOG_CONTENT]]
                }
              ]
            }" \
            "$LOKI_URL/api/prom/push"
