# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

name: Multi-Arch Release Linux JAX Wheels

on:
  workflow_call:
    inputs:
      amdgpu_family:
        type: string
        required: true

      release_type:
        type: string
        required: true

      rocm_version:
        type: string
        required: true

      tar_url:
        type: string
        required: true

      repository:
        type: string
        default: ""

      ref:
        type: string
        default: ""

  workflow_dispatch:
    inputs:
      amdgpu_family:
        type: choice
        options:
          - gfx101X-dgpu
          - gfx103X-all
          - gfx110X-all
          - gfx1150
          - gfx1151
          - gfx1152
          - gfx1153
          - gfx120X-all
          - gfx900
          - gfx906
          - gfx908
          - gfx90a
          - gfx94X-dcgpu
          - gfx950-dcgpu
        default: gfx94X-dcgpu

      release_type:
        type: choice
        options:
          - dev
          - nightly
          - prerelease
        default: dev

      rocm_version:
        type: string
        required: true

      tar_url:
        type: string
        required: true

      repository:
        type: string
        default: ""

      ref:
        type: string
        default: ""

permissions:
  contents: read
  id-token: write
  packages: read

run-name: Multi-Arch Release Linux JAX Wheels (${{ inputs.amdgpu_family }}, ${{ inputs.release_type }}, ${{ inputs.rocm_version }})

jobs:
  build_jax_wheels:
    name: Build Linux JAX Wheels (${{ inputs.amdgpu_family }}, py${{ matrix.python_version }}, ${{ inputs.release_type }})

    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.11", "3.12"]
        jax_ref: ["rocm-jaxlib-v0.9.1"]

    runs-on: ${{ github.repository_owner == 'ROCm' && 'azure-linux-scale-rocm' || 'ubuntu-24.04' }}

    steps:
      - name: Checkout TheRock
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || '' }}

      - name: Checkout rocm-jax
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          path: rocm-jax
          repository: ROCm/rocm-jax
          ref: ${{ matrix.jax_ref }}

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: ${{ matrix.python_version }}

      - name: Build JAX wheels
        env:
          ROCM_VERSION: ${{ inputs.rocm_version }}
        run: |
          pushd rocm-jax

          python3 build/ci_build \
            --compiler=clang \
            --python-versions="${{ matrix.python_version }}" \
            --rocm-version="${ROCM_VERSION}" \
            --therock-path="${{ inputs.tar_url }}" \
            dist_wheels

          popd