name: Release Linux PyTorch Wheels

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # Nightly at 2 AM UTC

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target: [gfx942, gfx1100, gfx1201]
        python_version: ["3.11", "3.12"]

    steps:
      - name: Set family based on target
        id: set_family
        run: |
          case "${{ matrix.target }}" in
            gfx942) echo "family=gfx94X-dcgpu" >> $GITHUB_OUTPUT ;;
            gfx1100) echo "family=gfx110X-dgpu" >> $GITHUB_OUTPUT ;;
            gfx1201) echo "family=gfx120X-all" >> $GITHUB_OUTPUT ;;
            *) echo "Unknown target: ${{ matrix.target }}" && exit 1 ;;
          esac

      - name: Call build workflow
        uses: ROCm/TheRock/.github/workflows/build_linux_pytorch_wheels.yml@main
        with:
          family: ${{ steps.set_family.outputs.family }}
          target: ${{ matrix.target }}
          python_version: ${{ matrix.python_version }}
          find_links: https://therock-nightly-python.s3.us-east-2.amazonaws.com/${{ steps.set_family.outputs.family }}/index.html
