name: Release Linux PyTorch Wheels

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # Nightly at 2 AM UTC

permissions:
  id-token: write
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { AMDGPU_FAMILIES: gfx94X-dcgpu }
          - { AMDGPU_FAMILIES: gfx110X-dgpu }
          - { AMDGPU_FAMILIES: gfx120X-all }
        python_version: ["cp311-cp311", "cp312-cp312"]

    uses: ./.github/workflows/build_linux_pytorch_wheels.yml
    with:
      AMDGPU_FAMILIES: ${{ matrix.config.AMDGPU_FAMILIES }}
      python_version: ${{ matrix.python_version }}
      s3_bucket: therock-nightly-python
