name: Release Linux PyTorch Wheels

on:
  workflow_dispatch:
    inputs:
      amdgpu_family:
        description: AMDGPU target family
        type: string
        required: true
      release_type:
        description: The type of release to build ("nightly", or "dev")
        type: string
        default: "dev"
      s3_subdir:
        description: S3 subdirectory, not including the GPU-family
        type: string
        default: "v2"
      cloudfront_url:
        description: CloudFront base URL pointing to Python index
        type: string
        default: "d25kgig7rdsyks.cloudfront.net/v2"
      # rocm_version:
      #   description: ROCm version to install (e.g. "==1.0", ">1.0")
      #   type: string
  schedule:
    - cron: "0 2 * * *"  # Nightly at 2 AM UTC

permissions:
  id-token: write
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["cp311-cp311", "cp312-cp312"]

    uses: ./.github/workflows/build_linux_pytorch_wheels.yml
    with:
      amdgpu_family: ${{ inputs.amdgpu_family }}
      python_version: ${{ matrix.python_version }}
      release_type: ${{ inputs.release_type || 'nightly' }}
      s3_subdir: ${{ inputs.s3_subdir || 'v2' }}
      cloudfront_url: ${{ inputs.cloudfront_url  || 'd2awnip2yjpvqn.cloudfront.net/v2' }}
      # rocm_version: ${{ inputs.rocm_version }}
