name: Release Linux PyTorch Wheels

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # Runs nightly at 2 AM UTC

permissions:
  id-token: write
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.11", "3.12"]
        include:
          - target: gfx942
            family: gfx94X-dcgpu
          - target: gfx1100
            family: gfx110X-dgpu
          - target: gfx1201
            family: gfx120X-all

    uses: ./.github/workflows/build_linux_pytorch_wheels.yml
    with:
      family: ${{ matrix.family }}
      python_version: ${{ matrix.python_version }}
      target: ${{ matrix.target }}
      find_links: https://therock-nightly-python.s3.us-east-2.amazonaws.com/${{ matrix.family }}/index.html
    secrets: inherit
