name: Release Windows PyTorch Wheels

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: The type of release to build ("nightly", or "dev")
        type: string
        default: "dev"
      s3_subdir:
        description: S3 subdirectory, not including the GPU-family
        type: string
        default: "v2"
      cloudfront_url:
        description: CloudFront URL pointing to Python index
        type: string
        default: "d25kgig7rdsyks.cloudfront.net/v2"

  # TODO(scotttodd): add schedule once working
  # schedule:
  #   - cron: "0 2 * * *"  # Nightly at 2 AM UTC

permissions:
  id-token: write
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { AMDGPU_FAMILIES: gfx110X-dgpu }
          # TODO(scotttodd): enable once nightly builds include these
          # - { AMDGPU_FAMILIES: gfx1151 }
          # - { AMDGPU_FAMILIES: gfx120X-all }
        python_version: ["3.11", "3.12"]

    uses: ./.github/workflows/build_windows_pytorch_wheels.yml
    with:
      amdgpu_family: ${{ matrix.config.AMDGPU_FAMILIES }}
      python_version: ${{ matrix.python_version }}
      release_type: ${{ inputs.release_type || 'nightly' }}
      s3_subdir: ${{ inputs.s3_subdir || 'v2' }}
      cloudfront_url: ${{ inputs.cloudfront_url  || 'd2awnip2yjpvqn.cloudfront.net/v2' }}
