name: Release Linux PyTorch Wheels

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [gfx942, gfx1100, gfx1201]
        python_version: ["3.11", "3.12"]
    uses: ROCm/TheRock/.github/workflows/build_linux_pytorch_wheels.yml@main
    with:
      target: ${{ matrix.target }}
      python_version: ${{ matrix.python_version }}
      family: ${{ fromJson('{"gfx942":"gfx94X-dcgpu","gfx1100":"gfx110X-dgpu","gfx1201":"gfx120X-all"}')[matrix.target] }}
      find_links: https://therock-nightly-python.s3.us-east-2.amazonaws.com/${{ fromJson('{"gfx942":"gfx94X-dcgpu","gfx1100":"gfx110X-dgpu","gfx1201":"gfx120X-all"}')[matrix.target] }}/index.html
