name: Release Linux PyTorch Wheels

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # Nightly at 2 AM UTC

permissions:
  id-token: write
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { AMDGPU_FAMILIES: gfx94X-dcgpu, PYTORCH_TARGET_ARCH: gfx942 }
          - { AMDGPU_FAMILIES: gfx110X-dgpu, PYTORCH_TARGET_ARCH: gfx1100 }
          - { AMDGPU_FAMILIES: gfx120X-all, PYTORCH_TARGET_ARCH: gfx1201 }
        python_version: ["3.11", "3.12"]

    uses: ./.github/workflows/build_linux_pytorch_wheels.yml
    with:
      AMDGPU_FAMILIES: ${{ matrix.config.AMDGPU_FAMILIES }}
      PYTORCH_TARGET_ARCH: ${{ matrix.config.PYTORCH_TARGET_ARCH }}
      python_version: ${{ matrix.python_version }}
      find_links: https://therock-nightly-python.s3.us-east-2.amazonaws.com/${{ matrix.config.AMDGPU_FAMILIES }}/index.html
