name: Setup

on:
  workflow_call:
    inputs:
      linux_amdgpu_families:
        type: string
      windows_amdgpu_families:
        type: string
      operating_system:
        type: string
    outputs:
      enable_build_jobs:
        description: Whether to enable build jobs.
        value: ${{ jobs.setup.outputs.enable_build_jobs }}
      linux_amdgpu_families:
        description: Linux families to run builds and tests on.
        value: ${{ jobs.setup.outputs.linux_amdgpu_families }}
      windows_amdgpu_families:
        description: Windows families to run builds and tests on.
        value: ${{ jobs.setup.outputs.windows_amdgpu_families }}

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-24.04
    env:
      # The commit being checked out is the merge commit for a PR. Its first
      # parent will be the tip of the base branch.
      BASE_REF: HEAD^
    outputs:
      enable_build_jobs: ${{ steps.configure.outputs.enable_build_jobs }}
      linux_amdgpu_families: ${{ steps.configure.outputs.linux_amdgpu_families }}
      windows_amdgpu_families: ${{ steps.configure.outputs.windows_amdgpu_families }}
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # We need the parent commit to do a diff
          fetch-depth: 2
      - name: "Configuring CI options"
        id: configure
        env:
          PR_LABELS: ${{ toJSON(github.event.pull_request.labels.*.name) }}
          INPUT_LINUX_AMDGPU_FAMILIES: ${{ inputs.linux_amdgpu_families }}
          INPUT_WINDOWS_AMDGPU_FAMILIES: ${{ inputs.windows_amdgpu_families }}
          BRANCH_NAME: ${GITHUB_REF#refs/heads/}
        run: ./build_tools/configure_ci.py
