name: Test AWS Runner (no container spec)

on:
  workflow_dispatch:
  push:
    branches:
      - test/aws-runner-no-container-spec

jobs:
  hello-world:
    runs-on: aws-linux-scale-rocm-prod
    steps:
      - name: Echo hello world
        run: echo "hello world"
