# Copyright 2025 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Test Linux Packages

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - ADHOCBUILD

  workflow_call:
    inputs:
      package_version:
        type: string
        default: ADHOCBUILD

permissions:
  id-token: write
  contents: read

jobs:
  test_rocm_info:
    name: "Sanity ROCM Test"
    runs-on: linux-mi300-1gpu-ossci
    strategy:
      fail-fast: true
    defaults:
      run:
        shell: bash
    env:
      VENV_DIR: ${{ github.workspace }}/.venv

    # MOSTLY BOILER PLATE ABOVE.
    steps:
      - name: Install the AWS tool
        run: sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::692859939525:role/therock-artifacts

      # TODO(): Replace id with ${{github.run_id}}
      - name: Download Unpack Artifacts
        run: |
          BUILD_ARTIFACTS_DIR=build/artifacts
          echo "Making ${BUILD_ARTIFACTS_DIR} directory"
          mkdir -p "${BUILD_ARTIFACTS_DIR}"

          echo "Downloading artifacts"
          aws s3 cp s3://therock-artifacts/13564590298/core-runtime_run.tar.xz "${BUILD_ARTIFACTS_DIR}"
          aws s3 cp s3://therock-artifacts/13564590298/core-runtime_lib.tar.xz "${BUILD_ARTIFACTS_DIR}"
          aws s3 cp s3://therock-artifacts/13564590298/sysdeps_lib.tar.xz "${BUILD_ARTIFACTS_DIR}"
          aws s3 cp s3://therock-artifacts/13564590298/base_lib.tar.xz "${BUILD_ARTIFACTS_DIR}"

          echo "Unpacking artifacts"
          set -x
          pushd "${BUILD_ARTIFACTS_DIR}"
          for a in *.tar.xz; do sudo tar -xvpf $(readlink -f .)/"$a" -C / --keep-directory-symlink; done
          set +x
          popd

      - name: Run rocminfo
        run: |
          echo "Running rocminfo"
          /bin/rocminfo