name: Test Linux Packages

on:
  workflow_dispatch:
    inputs:
      artifact_run_id:
        type: string
        default: ""
      amdgpu_families:
        type: string
        default: gfx94X-dcgpu
  workflow_call:
    inputs:
      amdgpu_families:
        type: string
        default: gfx94X-dcgpu
  push:
    branches:
      - ADHOCBUILD

jobs:
  test_sanity_check:
    name: 'Test Sanity Check'
    uses: './.github/workflows/test_sanity_check.yml'
    with:
      artifact_run_id: ${{ inputs.artifact_run_id }}
