name: TheRock BLAS math-lib tests

on:
  workflow_dispatch:
    inputs:
      artifact_run_id:
        type: string
        default: ""
      amdgpu_families:
        type: string
      test_runs_on:
        type: string
  workflow_call:
    inputs:
      artifact_run_id:
        type: string
        default: ""
      amdgpu_families:
        type: string
      test_runs_on:
        type: string
  push:
    branches:
      - ADHOCBUILD

jobs:
  test_blas:
    name: "BLAS math-lib test"
    runs-on: ${{ inputs.test_runs_on }}
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash
    env:
      VENV_DIR: ${{ github.workspace }}/.venv
      ARTIFACT_RUN_ID: "${{ inputs.artifact_run_id != '' && inputs.artifact_run_id || github.run_id }}"
      BUILD_ARTIFACTS_DIR: "./build/artifacts"
      THEROCK_BIN_DIR: "./build/artifacts/output_dir/bin"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install the AWS tool
        run: ./dockerfiles/cpubuilder/install_awscli.sh

      - name: "Setting up Python"
        id: setup_python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: 3.11

      - name: Create Python venv and installing packages
        run: |
          python -m venv ${VENV_DIR}
          source ${VENV_DIR}/bin/activate
          pip install -r requirements-test.txt
          sudo apt install gfortran -y

      - name: Download and Unpack Artifacts
        run: |
          source ${VENV_DIR}/bin/activate

          # TODO(sosa): We should infer this from the runner. For Libs and Above it should be based on the
          # runner, everything else is generic. Use just generic since this is all core/below.
          echo "Making ${BUILD_ARTIFACTS_DIR} directory"
          mkdir -p "${BUILD_ARTIFACTS_DIR}"

          echo "Downloading artifacts"
          python ./build_tools/fetch_artifacts.py \
            --run-id=${ARTIFACT_RUN_ID} \
            --target=${{ inputs.amdgpu_families }} \
            --build-dir=${BUILD_ARTIFACTS_DIR} \
            --test \
            --blas

          echo "Unpacking artifacts"
          mkdir ${BUILD_ARTIFACTS_DIR}/output_dir
          python ./build_tools/fileset_tool.py artifact-flatten ${BUILD_ARTIFACTS_DIR}/*.tar.xz -o ${BUILD_ARTIFACTS_DIR}/output_dir --verbose

      - name: Run hipBLASLt tests
        run: |
          source ${VENV_DIR}/bin/activate
          ${THEROCK_BIN_DIR}/hipblaslt-test --gtest_filter=*pre_checkin*

      - name: Run rocBLAS tests
        run: |
          ROCBLAS_TENSILE_LIBPATH="${BUILD_ARTIFACTS_DIR}/output_dir/lib/rocblas/library/"
          source ${VENV_DIR}/bin/activate
          ${THEROCK_BIN_DIR}/rocblas-test --yaml ${THEROCK_BIN_DIR}/rocblas_smoke.yaml
