name: Test Linux Packages

on:
  workflow_dispatch:
    inputs:
      artifact_run_id:
        type: string
        default: ""
      amdgpu_families:
        type: string
        default: gfx94X-dcgpu
      runs-on:
        type: string
        default: linux-mi300-1gpu-ossci-rocm
  workflow_call:
    inputs:
      amdgpu_families:
        type: string
        default: gfx94X-dcgpu
      runs-on:
        type: string
        default: linux-mi300-1gpu-ossci-rocm
  push:
    branches:
      - ADHOCBUILD

jobs:
  test_sanity_check:
    name: 'Test Sanity Check'
    uses: './.github/workflows/test_sanity_check.yml'
    with:
      artifact_run_id: ${{ inputs.artifact_run_id }}
      runs-on: ${{ inputs.runs-on }}

  test_blas:
    name: 'Test BLAS math-lib'
    uses: './.github/workflows/test_blas.yml'
    needs: test_sanity_check
    with:
      artifact_run_id: ${{ inputs.artifact_run_id }}
      amdgpu_families: ${{ inputs.amdgpu_families }}
      runs-on: ${{ inputs.runs-on }}
