name: TheRock Sharded Tests

on:
  workflow_dispatch:
  push:
    branches:
      - madkasul/delme_shardedTestWorkflow


permissions:
  contents: read
  packages: write

jobs:
  sharded_test_linux_nightly:
    name: ROCK Tests Linux Nightly
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 2

      - name: Run Tests
        run: |
          apt-get update
          apt-get install python3 python3-pip
          pip install kubectl
          kubectl -n rocmci get pods
          kubectl -n rocmci apply -f tests/sharding/spec.yaml
          sleep 30
          kubectl -n rocmci get pods
