# Copyright 2025 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Test Linux Packages

on:
  workflow_dispatch:
    inputs:
      package_version:
        type: string
        default: ADHOCBUILD

  workflow_call:
    inputs:
      package_version:
        type: string
        default: ADHOCBUILD

jobs:
  test_rocm_info:
    name: "Sanity ROCM Test"
    runs-on: linux-mi300-1gpu-ossci
    strategy:
      fail-fast: true
    defaults:
      run:
        shell: bash
    env:
      VENV_DIR: ${{ github.workspace }}/.venv

    # MOSTLY BOILER PLATE ABOVE.
    steps:
      - name: Install the AWS tool
        run: sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::692859939525:role/therock-artifacts

      - name: Download Unpack Artifacts
        run: |
          BUILD_ARTIFACTS_DIR="build/artifacts"
          # TODO(sosa): We should infer this from the runner. For Libs and Above it should be based on the
          # runner, everything else is generic. Use just generic since this is all core/below.
          VARIANT="_generic"
          echo "Making ${BUILD_ARTIFACTS_DIR} directory"
          mkdir -p "${BUILD_ARTIFACTS_DIR}"

          echo "Downloading artifacts"
          aws s3 cp s3://therock-artifacts/${{github.run_id}}/core-runtime_run"${VARIANT}".tar.xz "${BUILD_ARTIFACTS_DIR}"
          aws s3 cp s3://therock-artifacts/${{github.run_id}}/core-runtime_lib"${VARIANT}".tar.xz "${BUILD_ARTIFACTS_DIR}"
          aws s3 cp s3://therock-artifacts/${{github.run_id}}/sysdeps_lib.tar"${VARIANT}".xz "${BUILD_ARTIFACTS_DIR}"
          aws s3 cp s3://therock-artifacts/${{github.run_id}}/base_lib.tar"${VARIANT}".xz "${BUILD_ARTIFACTS_DIR}"

          echo "Unpacking artifacts"
          pushd "${BUILD_ARTIFACTS_DIR}"
          for a in *.tar.xz; do sudo tar -xvpf $(readlink -f .)/"$a" -C / --keep-directory-symlink; done
          popd

      - name: Run rocminfo
        run: |
          echo "Running rocminfo"
          /bin/rocminfo