name: TheRock PRIM math-lib tests

on:
  workflow_dispatch:
    inputs:
      artifact_run_id:
        type: string
        default: ""
      amdgpu_families:
        type: string
        default: gfx94X-dcgpu
      runs-on:
        type: string
        default: linux-mi300-1gpu-ossci-rocm
  workflow_call:
    inputs:
      artifact_run_id:
        type: string
        default: ""
      amdgpu_families:
        type: string
        default: gfx94X-dcgpu
      runs-on:
        type: string
        default: linux-mi300-1gpu-ossci-rocm
  push:
    branches:
      - ADHOCBUILD

jobs:
  test_sanity_check:
    name: "PRIM math-lib test"
    runs-on: ${{ inputs.runs-on }}
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash
    env:
      VENV_DIR: ${{ github.workspace }}/.venv
      ARTIFACT_RUN_ID: "${{ inputs.artifact_run_id != '' && inputs.artifact_run_id || github.run_id }}"
      OUTPUT_ARTIFACTS_DIR: "${{ github.workspace }}/build/artifacts"
      THEROCK_BIN_DIR: "${{ github.workspace }}/build/artifacts/output_dir/bin"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run test set-up workflow
        uses: './.github/workflows/test_setup_workflow.yml'
        with:
          ARTIFACT_RUN_ID: ${{ env.ARTIFACT_RUN_ID }}
          AMDGPU_FAMILIES: ${{ inputs.amdgpu_families }}
          OUTPUT_ARTIFACTS_DIR: ${{ env.OUTPUT_ARTIFACTS_DIR }}
          VENV_DIR: ${{ env.VENV_DIR }}
          FETCH_ARTIFACT_ARGS: "--test --prim"

      - name: Run rocprim tests
        run: |
          ctest --test-dir ${THEROCK_BIN_DIR}/rocprim --output-on-failure

      - name: Run rocthrust tests
        run: |
          ctest --test-dir ${THEROCK_BIN_DIR}/rocthrust --output-on-failure

      - name: Run hipcub tests
        run: |
          ctest --test-dir ${THEROCK_BIN_DIR}/hipcub --output-on-failure
