name: TheRock Sharded Tests

on:
  workflow_dispatch:
    inputs:
      amdgpu:
        type: string
        description: 'AMD GPU family to test. ex: gfx94X, gfx1201X'
        default: 'gfx94X'
      release:
        type: string
        description: 'The Rock Release version. ex: nightly-tarball (X.Y.ZrcYYYYMMDD) or dev-tarball (X.Y.Z.dev0+{hash})'
        default: '7.9.0rc20251008'
      tests:
        type: string
        description: 'The list of tests to run with "or" expression'
        default: 'hipcub or rocprim or rocrand or rocthrust'

permissions:
  contents: read

jobs:
  sharded_test_linux_nightly:
    name: TheRock Tests Sharded Linux Nightly
    runs-on: linux-mi325-1gpu-ossci-rocm
    env:
      AMDGPU: ${{inputs.amdgpu}}
      RELEASE: ${{inputs.release}}
      TESTS: ${{inputs.tests}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install TheRock
        shell: bash
        run: |
          set -x
          pip3 install -r requirements.txt
          python3 build_tools/install_rocm_from_artifacts.py --tests --amdgpu-family ${AMDGPU:-gfx94X}-dcgpu --release ${RELEASE:-7.9.0rc20251008}
      - name: Pre Requisites
        shell: bash
        run: pip3 install -r tests/sharding/requirements.txt
      - name: Running Sharded Tests
        shell: bash
        run: |
          set -x
          cd tests/sharding/
          python3 -m pytest -s -v --tb=short --rock=../../therock-build tests.py -k "${TESTS:-hipcub or rocprim or rocrand or rocthrust}"
