name: "okok yay"

on:
  push:
    branches:
      - release-test

jobs:
  generate_release_matrix:
    runs-on: ubuntu-24.04
    steps:
      - name: Checking out repository
        run: echo helloworld
