name: TheRock Sharded Tests

on:
  workflow_dispatch:
  push:
    branches:
      - madkasul/delme_shardedTestWorkflow


permissions:
  contents: read
  packages: write

jobs:
  sharded_test_linux_nightly:
    name: ROCK Tests Linux Nightly
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 2

      - name: Run Tests
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl
          curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key --output /tmp/Release.key
          sudo gpg --decrypt /tmp/Release.key --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
          echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl
          kubectl -n rocmci get pods
          kubectl -n rocmci apply -f tests/sharding/spec.yaml
          sleep 30
          kubectl -n rocmci get pods
