name: TheRock Sharded Tests

on:
  workflow_dispatch:
  push:
    branches:
      - madkasul/delme_shardedTestWorkflow

permissions:
  contents: read
  id-token: write

jobs:
  sharded_test_linux_nightly:
    name: TheRock Tests Sharded Linux Nightly
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 2

      - name: Run Tests
        env:
          KUBE_CONFIG: ${{ secrets.THEROCK_KUBE_CONFIG_SECRET }}
        run: |
          echo $KUBE_CONFIG >> kube_config
          kubectl --kubeconfig kube_config -n rocmci get pods
          kubectl --kubeconfig kube_config -n rocmci apply -f tests/sharding/spec.yaml
          sleep 30
          kubectl --kubeconfig kube_config -n rocmci get pods
