name: Pull and Verify Docker Image

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pull-and-build-image:
    name: "Verify Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/rocm/therock_pytorch_dev_ubuntu_24_04_gfx1201:main
      - name: Run Docker Container and Execute Commands
        run: |
          docker run --rm ghcr.io/rocm/therock_pytorch_dev_ubuntu_24_04_gfx1201:main /bin/bash -c "
            echo 'Running inside the container';
            python3 --version;  # Check Python version
            pip list;           # List installed Python packages
            echo 'Task completed!'
          "
      - name: Verify Containers Status
        run: docker ps -a
