name: Pull and Verify Docker Image

on:
  workflow_dispatch:
    inputs:
      amdgpu_target:
        description: "AMDGPU target to verify"
        required: true
        type: string

  workflow_call:
    inputs:
      amdgpu_target:
        required: true
        type: string

env:
  IMAGE_REF_NAME: ${{ github.ref_name }}

jobs:
  pull-and-build-image:
    name: Verify ${{ inputs.amdgpu_target }} Docker Image
    runs-on: linux-mi300-1gpu-ossci-rocm
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Sanitize tag values and build image ref
        id: sanitize
        run: |
          TARGET="${{ inputs.amdgpu_target }}"

          # # Sanitize values: lowercase, remove invalid characters
          SAFE_TARGET=$(echo "$TARGET" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_.-]/-/g')
          IMAGE_TAG=$(echo "$IMAGE_REF_NAME" | cut -d':' -f2 | tr '/' '-')
          IMAGE_REF="ghcr.io/rocm/therock_pytorch_dev_ubuntu_24_04_${SAFE_TARGET}:${IMAGE_TAG}"

          echo "IMAGE_REF=$IMAGE_REF" >> "$GITHUB_ENV"
          echo "Using image: $IMAGE_REF"
      - name: Pull Docker Image
        run: |
          docker pull "$IMAGE_REF"

      - name: Pre-download pytest wheel
        run: |
          mkdir -p pytest_wheels
          pip download pytest -d pytest_wheels
      - name: Run Docker Container and Execute Commands
        run: |
          docker run --rm \
          --device=/dev/kfd \
          --device=/dev/dri \
          --mount type=bind,source="$GITHUB_WORKSPACE/pytest_wheels",target=/wheels \
          --mount type=bind,source="$GITHUB_WORKSPACE",target=/TheRock \
          --group-add video \
          --cap-add=SYS_PTRACE \
          -w /TheRock \
          "$IMAGE_REF" \
          bash external-builds/pytorch/smoke-tests/run_smoke_tests.sh
      - name: Verify Containers Status
        run: docker ps -a
