name: Pull and Verify Docker Image

on:
  push:
  workflow_call:
  workflow_dispatch:
jobs:
  pull-and-build-image:
    name: Verify Docker Image
    runs-on: linux-mi300-1gpu-ossci-rocm
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/rocm/therock_pytorch_dev_ubuntu_24_04_gfx942:main
      - name: Run Docker Container and Execute Commands
        run: |
          docker run --rm --device=/dev/kfd --mount type=bind,source="$GITHUB_WORKSPACE",target=/workspace --device=/dev/dri --group-add video --cap-add=SYS_PTRACE ghcr.io/rocm/therock_pytorch_dev_ubuntu_24_04_gfx942:main /bin/bash
            echo 'Running inside the container';
            echo 'Check Python version';
            python3 --version;
            echo 'List the pip packages';
            pip list;
            echo 'Install pytest';
            PIP_BREAK_SYSTEM_PACKAGES=1 pip install -U --user pytest
            echo 'Run smoke tests';
            export PATH="$HOME/.local/bin:$PATH"
            pytest -v /workspace/external-builds/pytorch/smoke-tests/pytorch_smoke_tests.py
            echo 'Task completed!'
          "
      - name: Verify Containers Status
        run: docker ps -a
